### ISSUE TITLE
What happened to content model of `<source>`?

### ISSUE THREAD

**Issue by raffazizzi** [music-encoding/music-encoding#579] opened 2019-03-14 20:43 UTC
I was looking at [`<source>`](https://github.com/music-encoding/music-encoding/blob/develop/source/modules/MEI.header.xml#L2320) in v4 and noticed that it cannot contain `<identifier>` and `<titleStmt>` any longer. Is this intentional?

[The examples on the Guidelines](https://music-encoding.org/guidelines/v4/content/header.html#headerSourceDescription) still show those elements as children of `<source>`

**Comment by kepper** [comment] 2019-03-14 21:02
Hi Raff, yes, this is intentional. In v4, the double use of `<source>` for a) describing the material used to encode the file at hand and b) a frbr:manifestation has been removed. Now, `<source>` serves only the first purpose, while the latter is dealt with by a new `<manifestation>` element. `<source>` allows bibliographic content (`<head>`, `<bibl>`, `<biblStruct>`,…), while `<manifestation>` is closer to the  model of `<source>` in v3. 
However, I absolutely agree that this isn't clear at all. The problem is that our documentation isn't anywhere close to matching the state of v4. This affects both the Guidelines and the examples. Right now, Benni and I (as this year's Tech Chairs) are trying to get a better picture of the situation and come up with a plan to resolve this asap. Until the situation is resolved, the release of v4 is still an ongoing process, and we have to make it much clearer that this is still work in progress…

**Comment by bwbohl** [comment] 2019-03-15 08:56
The discussion leading towards this descision (in part) took l´place in:
* https://github.com/music-encoding/music-encoding/issues/478
* https://github.com/music-encoding/music-encoding/issues/61
* https://github.com/music-encoding/music-encoding/issues/546

**Comment by ahankinson** [comment] 2019-04-12 14:24
Can this be closed now?

**Comment by bwbohl** [comment] 2019-09-10 19:57
closing as now referenced from guidelines issue

**Closed as completed by bwbohl** 2019-09-10 19:57 UTC
Labels: Component: Core Schema, Priority: Medium, Type: Bug
