### ISSUE TITLE
Build fails on SVG error

### ISSUE THREAD

**Issue by yockyrr** [music-encoding/music-encoding#581] opened 2019-03-26 15:59 UTC
Attempting to build with command ``PATH_TO_XMLLINT="/usr/bin/xmllint" PATH_TO_JING="/usr/bin/jing" PATH_TO_SAXON_JAR="../saxon9he.jar" PATH_TO_TEI_STYLESHEETS="../Stylesheets" ./build.sh build`` gives this error: 
[mei-err.log](https://github.com/music-encoding/music-encoding/files/3008993/mei-err.log)

**Comment by frakel** [comment] 2019-03-29 11:25
Hi, 
the essential message in your error log is this line:
`Caused by: org.xml.sax.SAXParseException; systemId: http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/svg11.rng; lineNumber: 6; columnNumber: 3; The element type "hr" must be terminated by the matching end-tag "</hr>"`

To my opinion this is a bug in the TEIC/Stylesheets project as it does not resolve correctly the mentionned URL. Instead you get an 301 Error msg from the ngix server where the `hr` Error is detected.

We can solve this also by setting the URL to `https://www.tei-c.org/release/xml/tei/custom/schema/relaxng/svg11.rng` in the MEI sources or just in your odd file.
HTH, franz

**Comment by ahankinson** [comment] 2019-03-29 11:26
Is this a problem with the value currently set in the MEI sources?

**Comment by frakel** [comment] 2019-03-29 11:37
yes, seems to  be:
```
customizations\mei-all.xml:100:        <moduleRef url="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/svg11.rng"
customizations\mei-all_anyStart.xml:136:        <moduleRef url="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/svg11.rng"
customizations\mei-CMN.xml:95:        <moduleRef url="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/svg11.rng"
customizations\mei-Mensural.xml:95:        <moduleRef url="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/svg11.rng"
customizations\mei-Neumes.xml:95:        <moduleRef url="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/svg11.rng"
source\validation\mei_odds.odd:60:        <moduleRef url="http://relaxng.org/relaxng.rng"/>
```

**Comment by yockyrr** [comment] 2019-03-29 11:40
Can confirm that changing SVG links to HTTPS solves my issue.

**Comment by ahankinson** [comment] 2019-03-29 11:45
OK; thanks. I'll flag this as an urgent change

**Comment by ahankinson** [comment] 2019-03-29 11:50
I've filed a new tracking issue for this fix to go into the MEI core, so I will close this issue now.

**Comment by ahankinson** [comment] 2019-03-29 13:13
Re-opening so we can have a specific issue to fix, as per the Slack conversation.

**Closed as completed** 2019-03-29 13:37 UTC
Labels: Component: Core Schema, Priority: Critical, Type: Regression
