### ISSUE TITLE
cadenzas, note size, piano notation

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/music-encoding#406] opened 2017-02-16 09:53 UTC
Sometimes you want just the accidental printed in cue size but not the note.

**Comment by pe-ro** [comment] 2017-02-16 14:24
Sounds reasonble.

**Comment by pe-ro** [comment] 2017-02-16 15:08
But `<accid>` is already a member of `att.typography` which provides `@fontsize` --
```
<attDef ident="fontsize" usage="opt">
  <desc>Indicates the size of a font expressed in printers' points, i.e., 1/72nd of an inch,
    relative terms, e.g., "small", "larger", etc., or percentage values relative to "normal" size,
    e.g., "125%".</desc>
  <datatype>
    <rng:ref name="data.FONTSIZE"/>
  </datatype>
</attDef>
```
Is this not sufficient?

This has got me wondering though, if `att.relativeSize` is necessary, since all its members are also members of att.typography.  So instead of `size="cue"`, one could write `fontsize="small"`.  If that's too descriptive of rendition and not function, then we could add "cue" to data.FONTSIZETERM, making it permissible to say `fontsize="cue"`.  In effect, "cue" would be the functional equivalent of "small".

**Comment by rettinghaus** [comment] 2017-02-16 15:23
"cue" as a term *is* important for notation (and equals not necessarily "small"). 
I'm ok with dropping `@size` and adding "cue" to `data.FONTSIZETERM`.

**Comment by pe-ro** [comment] 2017-02-16 15:37
@craigsapp, @donbyrd, Is there any case where "cue" is not equal to "small"?  If there is any such case, then function and display are independent of each other and it wouldn't make sense to add "cue" to `data.FONTSIZETERM`.

**Comment by pe-ro** [comment] 2017-02-16 15:49
If it turns out we need to keep separate indications of a feature's size and it's "cue-ness", then I suggest we eliminate `att.relativeSize` (and therefore `@size`).  `@size` could then be replaced by `@cue` taking a boolean value.

**Comment by donbyrd** [comment] 2017-02-16 16:02
To my knowledge, "cue" always implies "small", but "small" certainly does _not_ imply "cue"! There are many examples of passages -- especially cadenza-like passages, but not always -- in small notes that are to be played. (I'm almost positive some have been cited in other issues.) So `@size` can't be eliminated.

**Comment by pe-ro** [comment] 2017-02-16 16:19
Yep, I'd forgotten about cadenzas.  But I think the name "size" is misleading because the attribute is actually recording *function* (that is, the note is / is not to be played in the absence of another performer).  Cadenza; that is, non-cue, notes should be encoded using  --
```
<note fontsize="small" cue="false"/>
```
or 
```
<note fontsize="small"/>
```
while notes as part of a cue may be encoded --
```
<note fontsize="small" cue="true"/>
```
or
```
<note cue="false"/>
```
or simply
```
<note/>
```

**Comment by kepper** [comment] 2017-02-16 16:54
I don't want to complicate things, but wouldn't it be more reasonable to identify a cadenza as such, and then (if that's not sufficient already) add a visual rendition of small to that. If we don't want to have a distinct <cadenza>, we could think about <span type"cadenza"> (suggested in some other thread…). An encoding merely saying that things are small seems to miss some semantics, sometimes…

**Comment by donbyrd** [comment] 2017-02-16 17:16
Identifying a cadenza as such might be a good idea, but it doesn't mean the notes are small! Anyway, the issue isn't only with cadenzas; as I said, "there are many examples of passages -- especially cadenza-like passages, but not always". Here's a "cadenza-like" passage (from Chopin Ballade no. 4, ed. by Joseffy):
![chopin_ballade4_smallnotes](https://cloud.githubusercontent.com/assets/1672175/23032136/83ff7f0c-f441-11e6-92a2-d3ef23dfb230.png)
And here's something that's not even remotely cadenza-like (from Debussy, Prélude a l'àpres-midi d'un faune, p. 1):
![debussy_smallnotes4harpgliss](https://cloud.githubusercontent.com/assets/1672175/23032242/c68c979c-f441-11e6-85c2-fd98fb419c09.png)

**Comment by pe-ro** [comment] 2017-02-16 19:44
I'm a little reluctant to introduce elements like `<cueSpan/>`, `<cadenzaSpan/>`, `<span type="cue"/>`,  or `<span type="cadenza"/>`.  Even though they're better semantic markup, getting anyone to use them (and use them properly) might be reaching too far at the moment.

I figured it would be better to work toward that slowly, first making sure that we're correctly addressing size and "cue-ness", "cadenza-ness", etc. at the note level.  Once that's done, I believe there's a foundation for introducing these spanning concepts.

@donbyrd, If the small notes in the Chopin aren't a cadenza, then what are they?

**Comment by donbyrd** [comment] 2017-02-16 20:32
Because it's so short, I'd call the small notes in the Chopin a cadenza-like passage, not a cadenza, but I suppose you could argue the other way. But no problem; how about this example? (From the Berceuse, Op. 57, Peters ed., p. 5)
![chopin_berceuse_smallnotes](https://cloud.githubusercontent.com/assets/1672175/23039712/85c698f0-f45c-11e6-9e91-2612fdc3dcff.png)
The meter is 6/8, as you'd guess. It's surprisingly easy to find this kind of thing in Chopin! Incidentally, you'll note that there are way too many 32nds in the right hand in the preceding measure. It's also pretty easy to find that in Chopin, though usually in small notes.

**Comment by pe-ro** [comment] 2017-02-16 23:17
For me "cadenza" and "cadenza-like" come with too much baggage.  I would describe the string of 32nds in m. 1 and the small notes in m. 2 as "quasi-improvisational".  In both cases, I don't think one is supposed to hear the individual notes, but rather the movement/gesture.  The fact that there are too many 32nds in m. 1 bolsters my claim, I believe, because not even the rhythm is precise.  In fact, the incorrect notation may be intentional; that is, a way of saying "don't take this stuff here too seriously".

I believe m. 2 is written the way it is in order to draw attention to the repetition of the A-flat in the right hand, but that just might be the ghost of Heinrich Schenker talking. 😀  In m. 1 the "run" could've (should've?) also been written with small notes (with perhaps the initial note being normal sized similar to m. 2).

In any case, the juxtaposition of these two different notational approaches to the same thing (i.e., semi-improvised material) reinforces your earlier statement that note size is not necessarily an indication of whether the note is part of a cue or quasi-improvisation.

Now I'm thinking @kepper may be right to suggest some kind of spanning element. The same approach has been taken with ligatures, beams, etc. (see #403 for discussion about applying it to coloration.) The question is, Where does this stop?  In other words, if we have `<ligatureSpan>`, `<beamSpan>`, `<cadenzaSpan>`, etc., then why not admit `<.*Span>`?  Alternatively, to halt the explosive growth in the number of elements we could create one element, `<span>`, that uses `@type` to specify its semantics and other attributes to capture its display properties.  The downside of this, of course, is that it will be difficult to enumerate all the values of `@type`.

**Comment by donbyrd** [comment] 2017-02-17 01:36
Okay, I agree that the string of 32nds in m. 1 and the small notes in m. 2 are "quasi-improvisational". Not only are there too many full-size 32nds in m. 1, but NB there are too many small 16ths -- even though they claim to be triplets! -- in m. 2.

But the juxtaposition of two different notational approaches to semi-improvised material does not quite reinforce my "earlier statement that note size is not necessarily an indication of whether the note is part of a cue or quasi-improvisation" because that's not quite what I said! I said, to my knowledge, "cue" always implies "small". So if notes are full-size, they're not part of a cue. Not only have I not seen an exception to that, I can't imagine a situation in which it'd make sense. Otherwise, though, I agree with your "not necessarily".

I'd say a run of small notes that aren't grace notes, i.e., that take (metric) time, is very likely quasi-improvisational, especially if the time doesn't add up. And a run of full-size _short-duration_ notes is probably quasi-improvisational if the time doesn't add up; if it does, it's probably not quasi-improvisational. Is that confusing enough?  :-)

**Comment by kepper** [comment] 2017-02-17 07:24
> 
> Alternatively, to halt the explosive growth in the number of elements we could create one element, <span>, that uses @type to specify its semantics and other attributes to capture its display properties. The downside of this, of course, is that it will be difficult to enumerate all the values of @type.

I believe that's the way to go. Otherwise we'd have to provide language for all kinds of repertoires with all kinds of weird notations. Right now we're focussing quite a bit on Chopin (whose scores sometimes give the impression of an repertoire of their own, and we clearly don't want to turn MEI into the CEI – Chopin Encoding Initiative…).

The main difference between the suggested <span/> and <beamSpan/> etc. would be that <beamSpan/> and the like are for control events, whereas I see <span/> as a milestone approach for events (knowing that this includes the corresponding control events). In a way, it is analogous to <section>, but without the structural problems. That is, you could use it to identify a musical theme in one of multiple voices, or dux and comes in fugues, or other analytical stuff. I'm aware that this may cause problems with multiple layers, but that's what @next / @prev and @plist are made for, I guess.

If it turns out that a specific situation requires a dedicated element (like <cadenzaSpan/>), we can still add that later, but it seems to be syntactic sugar (only). For now, an open list of suggested types seems sufficient. However, I wonder if we should use @type for this (I know I brought it up), or if @func would be more appropriate, given that @type is generally left without specific meaning in order to provide room for project-level use.

Sorry to bring that one up again, but since we're talking about spanning elements, this could be another opportunity to discuss the benefit of spanners for editorial markup. However, I would go for a <*Grp/> element in this case, since those elements don't necessarily follow the musical stream, and could extend into multiple staves. Question here is if we want to have individual elements (<addGrp/>, <delGrp/>,…) like we have for control events, or a single, type-able element that catches them all.

I know that the editorial spanner brings a whole lot of other problems to the table, and in fact I suggest to not conflate the whole discussion with this new problem. I'm just suggesting to keep this in mind in order to come to a consistent solution that might be transferrable later on to this area…

**Comment by rettinghaus** [comment] 2017-02-17 13:02
I just asked for the possibility to mark an accidental as "cue sized". I didn't want to call for a proper *functional* encoding as cue notes, cadenza or whatever (although I do think that this would be useful). 

And although cue notes are always printed as small notes, it doesn't have to mean (from a renderer's perspective) that a "cue *size*" is identical to a "small size". It could be that a text printed with `fontsize="small"` means 78% of the "normal" scale, whereas a cued (or better: cue sized) note head gets 73%  of a normal sized note head. 
So, apart from the general discussion about indicating the functional meaning of several notes, it would be ok to drop `@size` and instead add `cue` (as a *size*) to `data.FONTSIZETERM`.

**Comment by rettinghaus** [comment] 2017-02-17 15:00
Also it would be good to have an functional indicator for "real cue notes", showing that they originally belong to another voice, i.e. they are (on staff context) *visible* but not *audible*. Seems to me like a must-have for MEI to MIDI conversion.

**Comment by pe-ro** [comment] 2017-02-17 19:29
@donbyrd, I have to check Roemer again, but I believe that in jazz charts cues are often written as full-size notes, mostly because the score and parts are hand-written.  As @kepper points out, there is life beyond Chopin. 😀

**Comment by pe-ro** [comment] 2017-02-17 19:48
> I just asked for the possibility to mark an accidental as "cue sized".

@rettinghaus, got it. But the implications of your request (as well as your suggestion to consider the possibility of visible-but-not-audible notes) have to be explored at both the micro (note) and macro (note collection) levels. Sometimes even the simplest request can have far-reaching consequences that take time to work out.  I'm not trying to hold up or deny your request, only that slowing down to take notice of potential problems is a good thing.

**Comment by pe-ro** [comment] 2017-02-17 19:59
@kepper, I'm not denying that adding `<span>` might be useful, but how would it be different from `<annot>`?

**Comment by lpugin** [comment] 2017-02-17 20:05
I think we agreed that an annotation encoded with `<annot>` is something added on top of the content. See this thread https://github.com/rism-ch/verovio/issues/389

**Comment by kepper** [comment] 2017-02-17 20:09
As you know, my initial understanding of <annot> is really about an (editorial) annotation – the encoder wants to say something *about* the source. <span> would be used to say something about the music. I agree that it's not easy to draw a line somewhere in there, but maybe it's helpful to think of annotations as something explicitly not present in the source (hence it's often overlaid, printed at the margin / bottom / end, or other fancy ways of being available in a digital environment), while a musical theme (or similar things) are generally perceived as inherent to the music (though not being visible in most cases). Or, speaking in domains, <span> addresses the logical domain, while <annot> lives in the analytical (or maybe, if one wants to separate that out, editorial) domain.

I know my arguments aren't as crisp as they should be…

**Comment by pe-ro** [comment] 2017-02-17 21:09
Ok, so there's a difference of opinion about what an annotation is that needs to be worked out.  I'm inclined to retain `<annot>` as an editorial annotation and add `<overlay>` for the kind of thing Laurent is talking about.  It's all still a little fuzzy, but I'm thinking that an annotation may contain or even function as an overlay (I'm not sure which), but not vice versa.

And what might an `<overlay>` contain you ask.  Again, it's about as clear as mud, but I'm thinking it may contain almost anything, but most likely additional control events -- directives, tempo marks, etc.
The difference between these items and "regular" control events is that these should be rendered on top of the score **after it's laid out**.  That is, these items can overlap existing ones.  By contrast, the contents of an `<annot>`, if rendered, would behave "normally"; that is, they would participate in the usual layout process.

If the idea of an overlay offends, then perhaps another approach would be to use an attribute on control events to control whether they can overlap other stuff or not.  That way, there would be no need for `<overlay>`, but the function of `<annot>` would be clarified.

Of course, all this has implications with regard to editorial practice, but let's not entangle too many things at once.

Tell me if I'm getting warmer or colder ...

**Comment by donbyrd** [comment] 2017-02-18 13:00
I'm in Cleveland for the weekend, without easy access to various materials. But (1) @pe-ro, let me know what Roemer (that's Clinton Roemer, isn't it?) says about cue notes. (2) I like @rettinghaus'  suggestion about adding `cue` to `data.FONTSIZEITEM`. Not too long ago, we -- @craigsapp and me and I forget who -- discussed sizes of grace and cue notes relative to normal; we discovered that what SCORE does is somewhat different from what Gould recommends, and I doubt if every publisher (not to mention copyist or composer!) agrees with either.

**Comment by pe-ro** [comment] 2017-02-20 15:47
Roemer (2nd ed.) mentions cue notes twice.

p. 145 --
![image](https://cloud.githubusercontent.com/assets/5712877/23131206/2b48b36a-f757-11e6-9e50-b3f76dc363df.png)

p. 164 --
![image](https://cloud.githubusercontent.com/assets/5712877/23131159/0d8d8850-f757-11e6-927d-e44ecbfbcc49.png)

On p. 145 he indicates that cues should be written in small notes, but in the example on p. 164 the notes don't look all that much smaller to me.  Still, I suppose we should follow what he says, not what he does. 😀

**Comment by craigsapp** [comment] 2017-02-20 16:03
> Chopin (whose scores sometimes give the impression of an repertoire of their own, and we clearly don't want to turn MEI into the CEI – Chopin Encoding Initiative…).

Just wait until the Liszt Encoding Initiative...

Is anyone other than me working with encoding keyboard music?  

Piano notation is the most complex of any musical part to encode, so this is more about piano repertoires in general. You do not want to address it last just because it is difficult; otherwise, you will most likely have painted yourself into a corner before then.

Rough sorting of piano/keyboard music encoding difficulty:

* Scarlatti
* Bach
* Mozart
* Schubert
* Schuman
* Mendelssohn
* Haydn
* Beethoven
* Brahms
* CPE Bach
* Chopin
* Liszt
* Debussy
* Ravel

So Chopin is medium high in the list.

> clearly

clearly?

**Comment by pe-ro** [comment] 2017-02-20 16:12
> Piano notation is the most complex of any musical part to encode, so this is more about piano repertoires in general. You do not want to address it last just because it is difficult; otherwise, you will most likely have painted yourself into a corner before then.

+1

**Comment by craigsapp** [comment] 2017-02-20 16:28
> Sometimes you want just the accidental printed in cue size but not the note.

Yes, I have seen this in several editions as a variant on rendering editorial accidentals.  It would be good to discuss the separability of rendering and editorialness of an accidental.

Here are the main ways that I have seen editorial accidentals represented in scores:

<img width="877" alt="screen shot 2017-02-20 at 08 20 47" src="https://cloud.githubusercontent.com/assets/3487289/23133339/9a4646e0-f745-11e6-8f30-b22968ab4a8f.png">

A is the most common method for added musica ficta accidentals to a score, or in single-line/layer musical parts.  Not good for Baroque-era music since it can be confused with figured bass.

B is most common to fix an occasional obvious error in a score.

C is mostly for cautionary accidentals, but could be a variant of B.

D is for cases where there are more accidentals than in the case of B, or if the music is from the Baroque era, or the music is chordal (for which A is not possible).

For performance editions, D is the least disruptive for performers to read -- but might give problems to musicologists who want editorial markup to be more prominently displayed.

**Comment by donbyrd** [comment] 2017-02-20 17:25
Re @pe-ro 's comment about cues in the Roemer book, I agree that the cue notes on p. 164 aren't much smaller than the normal notes, but they are smaller, and on p. 145 they're definitely smaller, as he says. So I'd still say we know of no exceptions to the rule that cues are written with small notes.

**Comment by donbyrd** [comment] 2017-02-20 17:40
I don't have the nerve to give as detailed a list of relative difficulty as @craigsapp does, and I don't completely agree with him -- e.g., I think he underrates the complexity of Schumann -- but there's no question that "piano notation is the most complex of any musical part to encode". In our paper proposing a standard OMR testbed, Jakob Simonsen and I (have I've said this before w/r/t some issue or other? I have the feeling...) coined the term _pianoform_ notation, meaning notation involving:
• Structural interaction between the staves
• Structural interaction within a staff: interaction leading to three or more horizontal positions for the same logical time; voices appearing and disappearing anywhere; individual noteheads belonging to two or even three voices; interlocking beams; “impossible rhythms”
We give examples of all of these situations. We go on to say:

"We have never seen most of them in music for anything other than piano; and, for the following reasons, it is plausible that they are far more common in music for piano than for anything else. (Note that we are considering only music for 'popular' instruments, including human voice.)
"(a) The piano is widely used to play reductions of orchestral scores for accompaniments (often with large numbers of notes and voices in a very wide range)
"(b) The piano has a sustain pedal (allowing the player to keep any number of notes sounding at once)
":(c) It has a huge range: normally 88 semitones, the widest of any popular instrument (resulting in, e.g., voices needing to change clefs, sometimes by changing staves, and ottava signs)
"(d) It has been very popular from the 19th century on (when music became more complex and composers more interested in specifying details than previously)"

You say "But the organ has an even wider range! And the electric guitar has a sustain pedal! And..."? Read Appendix C of our paper (at http://homes.soic.indiana.edu/donbyrd/Papers/OMRStandardTestbed_figinline.pdf).

.

**Comment by donbyrd** [comment] 2017-02-21 13:40
I realize this issue is closed, but apropos of relative complexity of notation for piano vs. other instruments and notation by various composers, of the six figures the Appendix on pianoform notation in the aforementioned paper refers to, one is an Ives orchestral piece; the others are all piano music, including two Ravel and one each Brahms, Chopin, and Debussy. But, for examples of many of the horrors of piano music, I recommend my "Interesting Music Notation" page (http://homes.soic.indiana.edu/donbyrd/InterestingMusicNotation.html). 11 of the 13 examples there are unequivocally piano music. (One of the other two is Bach: definitely for keyboard, if not piano.)

**Comment by pe-ro** [comment] 2017-02-21 15:43
The individual note size aspect having been resolved, I've re-titled and re-opened this issue to reflect the change of direction of the discussion.  In the future, we should probably try harder to keep the discussion more focused.

**Comment by pe-ro** [comment] 2017-09-06 19:55
Closing this again, since the main issues have been resolved.

**Closed as completed by pe-ro** 2017-09-06 19:55 UTC
Labels: Component: Guidelines & Documentation, Priority: Medium, Type: Support Request
