### ISSUE TITLE
Lyric with chords

### ISSUE THREAD

**Issue by lpugin** [music-encoding/music-encoding#335] opened 2016-08-04 18:05 UTC
In some cases, it can be necessary to have chords with lyrics. Currently, it is only possible to have the lyrics as child of the notes. It would make sense to have the option to have them instaead as child of the chord. See examples and discussion in https://github.com/rism-ch/verovio/issues/267

**Comment by ahankinson** [comment] 2016-08-04 21:37
For the record, I disagree -- I put my reasons in the Verovio thread, so I won't fully re-hash them here, but just to say that a lyric belongs on a note and not on a chord since a voice cannot sing more than one pitch at a time.

**Comment by lpugin** [comment] 2016-08-05 07:14
I see what you mean. However, having a lyric on a chord is in itself not very logical, so your argument is being more catholic than the Pope. It creates additional issues, including making unclear whereas each lyric has to be rendered or not. Following the same logic as for `@dur` attributes or `artic` where the note "inherits" the chord values is clearer.

**Comment by ahankinson** [comment] 2016-08-16 09:41
I've been turning this over for a week now. If there _is_ a valid use case for lyrics on chords (see @donbyrd 's comments on  rism-ch/verovio#267) then just allowing lyrics on chords as a convenience method would seem to mix up the original intent.

**Comment by lpugin** [comment] 2016-08-16 09:44
What do you mean by mixing up the original intent? Sorry, I do not understand it.

**Comment by ahankinson** [comment] 2016-08-16 09:52
On Don's comment he notes that some composers have specifically written lyrics on chords. If we allow lyrics on chords as a 'convenience' function, then we cannot separate out those cases where the original intent of the composer is a lyric on a chord, or where it's simply been done as a convenience.

**Comment by lpugin** [comment] 2016-08-16 10:12
I can see two comments from Don (https://github.com/rism-ch/verovio/issues/267#issuecomment-238546270 https://github.com/rism-ch/verovio/issues/267#issuecomment-238546270) but none seems to be mentioning this.

In any case: how can you know what the original intent of the composer is? If there is a lyric attach to a chord, that is what you want to encode: the lyric attached to the chord applies to all notes. That is it.

Also, I find the playability (or "singability") a weird argument to bring up here. You cannot play or sing a note without duration, however notes in chords in MEI usually have no duration. But this is not the main point. The main point is that we often have in music notation things that are not playable. One example: four note chords for solo string instruments. They cannot be played, and musicians will just play the lower notes as arpeggios. (You will probably find unplayable things for every instruments.) So if the playable version has to be encoded, this belongs more to the gestural domain than to the visual one. For the string instruments chords, you might want to add a shorter `dur.ges` values to the lower notes that are not sustained through out the duration, but you would still encode them as normal chords since it is how their appear visually.

**Comment by ahankinson** [comment] 2016-08-16 10:21
Copy-and-paste @donbyrd 's comment so that it's here and not elsewhere:

> I asked Jay Gottlieb, a pianist specializing in contemporary music who's interested in unusual notation, for examples of music with with chords having accent marks or dynamics on individual notes. He said "The 2 emblematic composers who used what you're looking for were Messiaen and Stockhausen. M. first with the 4 Etudes de Rythme (1949-50) and S. with his Klavierstück I (1952) and of course in the others following." In a quick look through parts of the Etudes de Rythme, I didn't see anything, but Klavierstück I has several chords with different dynamics on individual notes. (The copy I was looking at, in the Music Library, had a comment pencilled in next to one of those chords: "I'd like to hear Karlheinz play this." :-) )

**Comment by ahankinson** [comment] 2016-08-16 10:22
Ah, nevermind -- I see that he's changed the title and the direction of the issue. :-/.

**Comment by ahankinson** [comment] 2016-08-16 10:30
A lyric on a chord is ambiguous. 99.9% of the time, if you have two voices and a lyric, it will be written on two layers with stems in opposite directions, and really meant for two performers.

My understanding is that a chord is a device used to indicate two simultaneous pitches **on a single instrument**. If there are two instruments simultaneously performing, the "best practice" is that they be notated as different voices on the same staff. Are there exceptions?

A chorded lyric makes no sense, since it is obviously for two distinct performers.

**Comment by craigsapp** [comment] 2016-08-16 10:48
> On Don's comment he notes that some composers have specifically written lyrics on chords. If we allow lyrics on chords as a 'convenience' function, then we cannot separate out those cases where the original intent of the composer is a lyric on a chord, or where it's simply been done as a convenience.

@ahankinson: Now discuss any analogies or lack of same for chords and articulations:

![screen shot 2016-08-16 at 12 10 01 pm](https://cloud.githubusercontent.com/assets/3487289/17695795/784e6790-63aa-11e6-9eaf-8f69a7c5e814.png)

``` xml
<measure>
  <staff>
    <layer>
      <chord dur="4">
        <note oct="4" pname="d" accid.ges="n" />
        <note oct="4" pname="b" accid.ges="n" />
        <note oct="5" pname="g" accid.ges="n" />
        <artic artic="stacc"/>
      </chord>
    </layer>
  </staff>
</measure>
```

Is this not the correct encoding of a staccato on a chord?  All three chord notes share the same articulation, so the articulation is moved out of the individual note elements and placed on the chord level.  Why should lyric syllables be handled different than articulations?  If they are handled differently, then this will increase the cost of implementation and maintenance of software. 

Is the following encoding correct and/or well-formed?

``` xml
<measure>
  <staff>
    <layer>
      <chord dur="4">
        <note oct="4" pname="d" accid.ges="n" artic="stacc" />
        <note oct="4" pname="b" accid.ges="n" artic="stacc" />
        <note oct="5" pname="g" accid.ges="n" artic="stacc" />
      </chord>
    </layer>
  </staff>
</measure>
```

And what about this encoding:

``` xml
<measure>
  <staff>
    <layer>
      <chord dur="4">
        <note oct="4" pname="d" accid.ges="n" artic="stacc" />
        <note oct="4" pname="b" accid.ges="n" artic="stacc" />
        <note oct="5" pname="g" accid.ges="n" artic="stacc" />
        <artic artic="stacc"/>
      </chord>
    </layer>
  </staff>
</measure>
```

As a side note, here is the Guido Music Notation for the same music:

``` guido
[    \stacc(  {d,b,g2}  )    ]
```

Notice that there is one staccato which is applied to three notes.  Also, there is a fundamental bug in the Guide Music Notation engine, which has been there for over ten years after I first reported it:

![screen shot 2016-08-16 at 12 28 55 pm](https://cloud.githubusercontent.com/assets/3487289/17696184/0f9d364c-63ad-11e6-8b44-1f0ab9e01809.png)

They are mixing up the meaning (a.k.a. gestural) and notational syntaxes.  The encoding uses a notational syntax, but the GMN rendering engine displays with a gestural syntax.

Humdrum encoding of the same example:

```
**kern
4d' 4b' 4gg'
*-
```

Humdrum prefers maximally localized information about notes, so it is gesturally biased.  When converting to representations focused on notational syntax, such as MEI, I only read the articulation on the first note listed in the chord (4d').  If you don't think MEI is notationally biased, see the recent discussions on accidentals :-)

**Comment by craigsapp** [comment] 2016-08-16 11:31
> My understanding is that a chord is a device used to indicate two simultaneous pitches on a single instrument. If there are two instruments simultaneously performing, the "best practice" is that they be notated as different voices on the same staff. Are there exceptions?

Here are some scores of Beethoven's 5th symphony:

http://imslp.org/wiki/Symphony_No.5,_Op.67_(Beethoven,_Ludwig_van)

Observe the notation of the Clarinets in the opening of 

Ludwig van Beethovens Werke, Serie 1: Symphonien, Nr.5 
Leipzig: Breitkopf und Härtel, 1862. Plate B.5.

http://javanese.imslp.info/files/imglnks/usimg/0/0c/IMSLP52624-PMLP01586-Beethoven_Werke_Breitkopf_Serie_1_No_5_Op_67.pdf
![screen shot 2016-08-16 at 1 03 21 pm](https://cloud.githubusercontent.com/assets/3487289/17696949/18caabd2-63b2-11e6-9eaa-cc3092b22519.png)

But on the next page in the clarinet parts, the two parts share the same stem:

![screen shot 2016-08-16 at 1 06 40 pm](https://cloud.githubusercontent.com/assets/3487289/17696986/561e5bc8-63b2-11e6-8c50-52911badeb30.png)

There are more verbose orchestral score syntaxes where the stems are not merged, and parts would not share rests (none available in IMSLP).

There are also more compact orchestral score syntaxes, where the parts are merged further, such as the Eulenberg edition:

http://ks.imslp.info/files/imglnks/usimg/0/00/IMSLP09344-Beethoven_-_Symphony_No.5_Mvt.I__ed._Unger_.pdf

![screen shot 2016-08-16 at 1 11 29 pm](https://cloud.githubusercontent.com/assets/3487289/17697093/04891c98-63b3-11e6-8b62-40a5bee90d4f.png)

However, for lyrical text, the syntax would be more similar to the violins in these scores.  There are multiple violinists which play from a single part.  There may be divisi in the part, where half of the instruments play one note and the other have play another note.  This could be notationally represented in multiple ways depending on editorial styles, but all having the same "meaning".  The divisi notes could share the same stem, or have separate stems.

It seems to me that the chord syntax of MEI is specifically related to the visual display of the notation, not to a more abstract concept related to meaning or intention regarding voices (notice that layers are called `<layer>`, not `<voice>`.  The _meaning_ of a `<chord>` in MEI is that notes share a common stem (or should share a stem if they were not whole notes).  When there are more than two stems occurring at the same time, then these notes must be placed in different layers, one layer for each group of stemmed notes occurring at the same time.  I have not heard any MEI discussions about transforming MEI scores between these different types of scores.   So this might also be a good new point for discussion, as this sort of manipulation seems antithetical to the current capabilities of MEI.  And if you want a `<chord>` to imply a gestural rather than notational meaning to the music, then the discussion will basically follow the one for accidentals: if you want both, then there will probably have to be an indication in the header as to which should apply in the following musical data.

**Comment by donbyrd** [comment] 2016-08-16 13:30
There's a fair amount of confusion in this discussion, aside from the complexity of the issues.
(1) As Laurent said, I made only two comments on issue #267. Neither even mentions lyrics.
(2) I didn't "change the title and the direction of the issue [#267]"; I changed the title in response to the fact that the direction had already changed. That was an attempt to clarify matters. Laurent also (it seems to me) attempted to clarify things by opening this thread. Based on the current level of confusion, I'd say both our efforts failed completely :-) . One reason is I didn't realize that issue #267 is for Verovio, but this one is on music-encoding. Maybe I'm not the only person with that problem? Anyway, I placed my comment giving an example of notes in a chord with different dynamics in Verovio issue 267, in accord with its expanded scope. Andrew understandably copied it here. So maybe this issue should also be renamed something like "Chords with notational features (lyrics, accents, dynamics, etc.) on individual notes"?

**Comment by craigsapp** [comment] 2016-08-16 13:36
I was just using articulations here as a talking point for how lyric syllables should/might be represented in MEI, so it is somewhat of a coincidence that it maps also to the other thread.  Did you check the  Stockhausen/Messiaen pieces for the articulations on individual notes in chords?  They are pretty rare, but would be an example case where there should be an articulation on individual note(s)s in a chord rather than a shared articulation on a chord containing the notes that should all be played with that articulation.

**Comment by donbyrd** [comment] 2016-08-16 13:39
As for the issues, Craig's response to the comment that "If there are two instruments simultaneously performing, the "best practice" is that they be notated as different voices on the same staff. Are there exceptions?" is excellent. I'd just add that it might be_best_ practice to do that in some sense, but it's _standard_ practice in 19th century and later orchestral scores to show two or three of the same type of wind instrument on a single staff. In that case, when both or all three are in rhythmic unison, the noteheads are usually on a single stem.

Also, w/r/t Laurent's comment that a lot of notation is unplayable, I'd say rather that a lot of notation can't be taken literally, though even that is less clear than one might think. For example, it's true that modern bowed strings can't sound four notes simultaneously, but Baroque instruments, with their flatter bridges, probably could. However, the Ysaye sonatas for solo violin, Op. 27, contain chords with six or seven notes! Anyway, as Laurent says, string players will just arpeggiate chords with lots of notes and sustain as many as they can.

**Comment by donbyrd** [comment] 2016-08-16 13:42
Re Craig's question as to whether I "check[ed] the Stockhausen/Messiaen pieces for the articulations on individual notes in chords?": Yes, I did, and I didn't see any. However, I looked at only part of the Messiaen and only no. 1 of Stockhausen's many Klavierstücke.

**Comment by donbyrd** [comment] 2016-08-16 19:06
Incidentally, there's at least one notational feature that's commonly applied to individual notes of a chord: fingerings.

**Comment by craigsapp** [comment] 2016-08-16 19:18
And how to place them is probably not something that can be done automatically very well:

![screen shot 2016-08-16 at 9 08 44 pm](https://cloud.githubusercontent.com/assets/3487289/17712361/d4640490-63f5-11e6-8b40-6f693052a6e0.png)

(Chopin Etude 25/6, Berlin: Bote & Bock, n.d.[1880]. Plate 12282)

I like putting the fingering on a line away from the music for practicing:

![screen shot 2016-08-16 at 9 15 07 pm](https://cloud.githubusercontent.com/assets/3487289/17712526/9f9b2f08-63f6-11e6-94ba-bfb6f4e67699.png)

**Comment by craigsapp** [comment] 2016-08-17 13:43
I just happen to come across another case where I need lyric syllables attached to chords (or attached to a single note in the chord as might be more appropriate in this case):

![screen shot 2016-08-17 at 3 31 38 pm](https://cloud.githubusercontent.com/assets/3487289/17738089/17282988-6490-11e6-8650-bc32201cb6b9.png)

In this case the music is for piano, but there is a vocal part which shares the music with the piano (following the top melodic notes of the piano part). 

So in this particular case the last three chords need text underneath them, but it _will_ only be the top note of each chord which is associated with the syllable (the other note will be played by the piano alone).

How to interpret the "meaning" of this when encoded in MEI is an interesting topic.  Is there a way to indicate that particular notes in such condensed scores are to be shared between two instruments?  How could a MIDI file with voice & piano parts be extracted from such as MEI encoding?  How should/could the melody of the vocal part be extracted from the condensed score?

**Comment by ahankinson** [comment] 2016-08-17 14:25
You could use `@layer`, and then assign the notes to both the piano and voice layers.

**Comment by donbyrd** [comment] 2016-08-17 14:45
Here's an interesting common case. The vast majority of the music in my hymnal has four parts, but displayed on two staves, (1) to save space and (2) so a pianist can play along. The result is that almost every page has several two-note chords with lyrics that belong equally to both notes.

And here's an interesting and very unusual case. In Stravinsky's The Flood, God's words are sung by a duet of basses, most if not all of the time in rhythmic unison but at different pitches (IMO, an absolute stroke of genius, but Stravinsky had quite a few of those :-) ). I've never seen the score, but I'd guess God's part is full of two-note chords on a single stem, again with lyrics that belong equally to both notes.

**Comment by craigsapp** [comment] 2016-08-17 15:25
> You could use @layer, and then assign the notes to both the piano and voice layers.

As long as it is verovio-compliant :-)

Something like:

``` xml
   <note layer="1 2">
```

Are there encoding samples related to this?

Here is another measure where the piano part has two layers, but the voice has one (of course):

![screen shot 2016-08-17 at 5 11 50 pm](https://cloud.githubusercontent.com/assets/3487289/17741846/0e92a2a4-649e-11e6-8946-3077ded92951.png)

(notice the lyrics missing from the first three chords in the measure in Verovio, but "tu" is visible because it is attached to only the top layer note).

So this example would need a way of indicating the voice layer, since assigning it to "2" would not work, since sometimes the piano part needs more layers?

**Comment by pe-ro** [comment] 2016-08-25 18:29
Having a "notational bias" is a feature, not a bug. :-|

Since there is notation where lyrics are assigned to chords, it seems logical to me that MEI follow suit.

**Comment by lpugin** [comment] 2016-08-29 13:21
@pe-ro does this mean you agree to have lyrics directly as child of a chord?

**Comment by pe-ro** [comment] 2016-08-29 13:55
Yes.

**Comment by ahankinson** [comment] 2016-08-29 18:06
I still think this is a Bad Idea™.

**Comment by lpugin** [comment] 2016-08-29 18:54
> My understanding is that a chord is a device used to indicate two simultaneous pitches on a single instrument. If there are two instruments simultaneously performing, the "best practice" is that they be notated as different voices on the same staff. Are there exceptions?

This is a music notation writing issue. That is, your best practice is about how to notate this. Now if it was written as a chord, our role is to find a way to encode this appropriately, and it seems that a `chord` with the lyrics in it is the closest we can get.

**Comment by pe-ro** [comment] 2016-08-29 19:07
@ahankinson: I agree that it's not without its pitfalls, but it's a straightforward approach for homophonic settings like hymns.  I don't see a huge harm in it, since the current practice will still be supported.

In my opinion, the following is preferable as it's more explicit and therefore requires less effort to process for non-display purposes (like performance and analysis) --

```
<staff n="1">
  <layer n="1">
    <note stem.dir="up">
      <lyrics>
        <verse>
          <syl>Do</syl>
        </verse>
      </lyrics>
    </note>
  </layer>
  <layer n="2">
    <note stem.dir="up">
       <lyrics>
         <verse>
          <syl>Do</syl>
        </verse>
      </lyrics>
    </note>
  </layer>
</staff>
```

But, I also recognize the desire/need for --

```
<staff n="1">
  <layer n="1">
    <chord stem.dir="up">
      <note/>
      <note/>
      <lyrics>
        <verse>
          <syl>Don't</syl>
        </verse>
      </lyrics>
    </chord>
  </layer>
</staff>
```

which may be useful in some situations, for example, when converting from systems that allow this in their data model or when the markup is generated by our favorite naive encoder.  It's also in line with the markup of articulation marks, etc. when they're shared by all the notes in a chord.

**Comment by donbyrd** [comment] 2016-08-29 20:45
FWIW, I concur with @lpugin and @pe-ro. W/r/t the idea that 'If there are two instruments simultaneously performing, the "best practice" is that they be notated as different voices on the same staff'. Are there exceptions?':  As I said before, there are a great many orchestral scores that _don't_ notate them as different voices when they're in rhythmic unison. When there are _three_ instruments simultaneously playing and in rhythmic unison, they're very rarely notated as different voices, and I'd say that (writing them as chords) is definitely best practice.

**Comment by craigsapp** [comment] 2016-08-29 23:01
@pe-ro: This encoding seems to be in violation of the current graphical syntax with respect to layers:

> ``` xml
> <staff n="1">
>   <layer n="1">
>     <note stem.dir="up">
>       <lyrics>
>         <verse>
>           <syl>Do</syl>
>         </verse>
>       </lyrics>
>     </note>
>   </layer>
>   <layer n="2">
>     <note stem.dir="up">
>        <lyrics>
>          <verse>
>           <syl>Do</syl>
>         </verse>
>       </lyrics>
>     </note>
>   </layer>
> </staff>
> ```

Here are several graphic interpretations of the above data:

![screen shot 2016-08-30 at 12 23 11 am](https://cloud.githubusercontent.com/assets/3487289/18069537/21db8f2a-6e48-11e6-8a19-27f602808063.png)

In particular, the third one is the most reasonable graphic interpretation of the encoding.  If two different layers have stems in the same direction, then the stems must be offset to indicate that they are in separate layers.  I don't see how you can do anything but retract the above encoding :-)  Otherwise, there would have to be the invention of a stem floating element which groups notes in separate layers into one shared stem.   And beams would then attach to this stem element rather than to the notes, and etc. as things might start to get messy.   Something of the sort would be useful with application into generating scores and parts from the same digital encoding.  This is in the domain of MuseData (an aspect that was _not_ adopted by MusicXML).   The MuseData printing system has two formats:  one for abstract digital encodings closer to Humdrum, and another "compiled" representation which transforms the abstract form into a visual form closer to SCORE.

For the words, I still don't understand how a renderer would know what to do with such an encoding.  In particular there is one syllable, but you are putting two in the encoding.  Why this redundancy?   Should the syllables overstrike for both notes, should they be placed one above the other, should one syllable be placed above the staff?   If they are supposed to be overstriking, then what would happen if the syllables were not the same?   I see that someone still is a WizeGuy  &#8482;, and the problems discussed in the previous paragraph would have to be solved/addressed before an encoding in this direction were to be acceptable.

**Comment by ahankinson** [comment] 2016-08-30 06:38
@craigsapp I believe Perry was being concise for illustrative purposes.

If there are two notes then there are two simultaneous syllables, even if they are the same. This is pretty obvious since:
1. A syllable can only be realized (sung, performed) by a human, and
2. A human can only sing one note at a time

How a renderer chooses to display that is separate from how it is encoded. You may want to collapse the two syllables in your software, but I may want to keep them separate. 

If the syllables were not the same, we wouldn't be having this discussion since they would need to be encoded at the note level anyway.

**Comment by lpugin** [comment] 2016-08-30 07:15
> How a renderer chooses to display that is separate from how it is encoded. You may want to collapse the two syllables in your software, but I may want to keep them separate.

Where MEI is used to encode what is represented on an existing source (its primary purpose) the encoding should not be ambiguous about the fact that a syllable is appearing twice or is collapsed. This is actually not a rendering issue.

If somebody wrote chords with a single line of lyrics underneath, with a lyric as child of the chord the encoding is crystal clear for analysis, sound rendering and visual rendering. If two syllables are written (maybe both underneath, or one above and one below), then encoding them with the lyrics attached to the note is also perfectly clear for any usage. Why make things more complicated?

**Comment by craigsapp** [comment] 2016-08-30 07:55
> 1. A syllable can only be realized (sung, performed) by a human, and
> 2. A human can only sing one note at a time
1. Parrots can sing, and what about leaving open the possibilities of alien lifeforms who have two vocal tracts?
2. I still fail to see the point.  

> How a renderer chooses to display that is separate from how it is encoded. You may want to collapse the two syllables in your software, but I may want to keep them separate.

You argue from a Humdrum direction, and `@kepper`  argues from a SCORE direction.  I will point out that neither of you sufficiently know Humdrum or SCORE.  Both of you please become more familiar with both of these formats, or it is difficult for me to communicate with you.  Both of these formats have much more clearer meanings tied to their representation of music.  Humdrum is concerned with representing the musical meaning of the data (though which computers can be allowed to manipulate and analyze the musical data), while SCORE is more concerned with the graphical expression of the music (though which a composer communicates with performers).  Mapping between these representations is difficult, but they are much more internally self-consistent than MEI currently is.   Inconsistent data cannot be automatically processed.  It seems that MEI can be locally self-consistent for a particular project, but I am wondering how it can be globally consistent across multiple projects.   This is one reason why more examples are necessary for the documentation, along with some sort of best-practices and acceptable-practices guidelines which are easy to navigate.  Lilypond documentation is somewhat along these lines.

In both Humdrum and SCORE, such a case can be encoded in different ways.  

Here is how you are mostly wanting to encode the music, as two separate voices with two separate lyric syllables:

```
**kern  **text  **kern  **text
4c      Do      4cc     Do
*-      *-      *-      *-
```

This is the most convenient encoding for music analysis.  Since Humdrum data has no explicit graphical representation, this could be displayed in musical notation any way the renderer wants.   For example, a closer representation to the graphical score where I came across this sort of example:

```
**kern  **text
4c 4cc  Do
*-      *-
```

This is what `@kepper` wants (not that I mean to put words in his mouth :-).  In other words, this is what I see in the score, and I apply a minimal interpretation to derive the digital encoding.   This is also the primary way users of Finale/Sibelius/MuseScore would need to use to get the correct graphical rendering and hence in MusicXML export.

Notice that MEI has a note bias, with the lyrics attached to the notes.  Humdrum does not have this bias, and the text is an independent stream of equal weighting.  I could also represent this example like this:

```
**kern          **text
*^              *
4c  4cc         Do
*v  *v          *
*-              *-
```

The above case means that there are two independent sub-streams of notes (one for each divisi part), and there is a single text syllable that they share.    This is a better representation than the one you are suggesting and @pe-ro provided for this case.

You and @pe-ro support this encoding, where there is a single part that splits into two single-note layers, each with a separate lyric syllable:

```
**kern      **text
*^          *^ 
4c  4cc     Do  Do
*v  *v      *v  *v
*-          *-
```

This is mostly because MEI cannot represent the previous example where there is a single syllable shared by two voices (other than attaching the syllable to the chord as I do in the second Humdrum example above.

**Comment by ahankinson** [comment] 2016-08-30 08:02
Since I'm (apparently) not educated enough to participate in this conversation, I won't waste your time any more -- please accept my apologies for presuming to know something about it.

I'm not going to stand in the way of any changes, I just wanted to register and argue my dissatisfaction with it. It's not a particularly important hill to die on, so I won't argue any further.

**Comment by lpugin** [comment] 2016-08-30 08:15
I am sure we all agree this is not a crucial discussion topic. So if there is no other dissatisfaction than the one of @ahankinson , I would suggest to move on and to allow the lyrics to be child of a chord. I am sorry we do not reached a complete consensus in this, but again, it is a very minor topic. Further more we are not precluding people to encode them as up to now if they feel it is more appropriate in their case.

**Comment by pe-ro** [comment] 2016-08-30 17:33
In the grand scheme of the Universe, none of this stuff is as important as maintaining a good working relationship.  Because we've all known each other and worked together in various capacities for a long time, it's easy to slip into a too-familiar, dismissive tone.  Please remember, a written remark can be perceived very differently from the same remark when spoken, often in a way not intended by the writer.  So, it's crucial that we keep the exchanges here professional and cordial.

I'm not pointing a finger, mostly because I, like everyone else at some point, haven't always lived up to these expectations.  Let's just call this a "miscommunication" between colleagues and friends and move forward.

**Comment by pe-ro** [comment] 2016-08-30 18:17
I'll concede that it's sometimes useful to view MEI as either Humdrum-like, SCORE-like, or something else-like. But one of the things (if not "the" thing) that sets MEI apart from its predecessors, is its intention to accommodate more than one approach simultaneously.  Granted, this makes the software developer's job somewhat more difficult, but because these representations have mostly already been implemented in previous programs, the job isn't impossible.  The task is to work out when MEI is fish-like, when it's fowl-like, and how to tell the difference.

> Here is how you are mostly wanting to encode the music, as two separate voices with two separate lyric 
> syllables:
> 
> ```
> **kern  **text  **kern  **text
> 4c      Do      4cc     Do
> *-      *-      *-      *-
> ```
> 
> This is the most convenient encoding for music analysis. Since Humdrum data has no explicit graphical 
> representation, this could be displayed in musical notation any way the renderer wants.

MEI is no more or less "internally inconsistent" here than Humdrum, since Humdrum itself allows this markup approach.  And I did say in my earlier comment that this kind of encoding is best suited for "non-display purposes (like performance and analysis)".  If it's admissible in Humdrum and can be rendered with "minimal interpretation", I don't think it should be excluded in MEI.  Human intervention (via program parameters or rendering hints in the markup) may be required sometimes, but programmatically reducing it or  

> ```
> **kern      **text
> *^          *^ 
> 4c  4cc     Do  Do
> *v  *v      *v  *v
> *-          *-
> ```

to

> ```
> **kern  **text
> 4c 4cc  Do
> *-      *-
> ```

or the MEI equivalent shouldn't be overly difficult in most cases.

By the way, while it may not have come up yet in Verovio development and I've left out the details of the association between each syllable of the lyrics and the individual notes, MEI is, in fact, capable of representing two independent streams of notes and a single text syllable that they share --

```
<measure>
  <staff n="1">
    <layer n="1">
      <note stem.dir="up"/>
    </layer>
    <layer n="2">
      <note stem.dir="up"/>
    </layer>
  </staff>
  <lyrics staff="1" layer="1 2">
    <verse>
      <syl>Do</syl>
    </verse>
  </lyrics>
</measure>
```

Of course, this encoding requires a certain level of interpretation by the renderer as well, but that's true of any/all representation schemes.

**Closed as completed** 2017-01-10 14:59 UTC
Labels: Component: Core Schema, Priority: Low, Type: Feature Request
