### ISSUE TITLE
Extend curve direction for s-shaped slurs

### ISSUE THREAD

**Issue by brdvd** [music-encoding/music-encoding#912] opened 2022-02-16 09:35 UTC
The available values of `@curvature.curvedir` are insufficient when it comes to encoding s-shaped slurs. It is impossible to distinguish between the following shapes:
![MixedShapes](https://user-images.githubusercontent.com/63608463/154234420-f22ccf46-cb3a-43de-96d8-bfd40dea87f5.png)
For s-shaped cross staff slurs the shape can be deduced following Gould p. 321:
![Cross-staff](https://user-images.githubusercontent.com/63608463/154235009-04f2f46c-128b-4158-9ddc-1e7ea726c32a.png)
However, for s-shaped slurs within a single staff the choice of shape must be encoded.

One suggestion would be to replace `curvature_CURVEDIR_mixed` by `curvature_CURVEDIR_mixed_above_below` and `curvature_CURVEDIR_mixed_below_above`. I am not happy with these long names, so feel free to propose better names.

**Comment by ahankinson** [comment] 2022-02-16 09:38
Can I check your use case to see *why* this should be specifically encoded? 

Is it not sufficient to simply say there should be a slur between point a and point b, and then rely on the rules for the renderer to draw it appropriately?

**Comment by brdvd** [comment] 2022-02-16 09:50
Consider the following example:
| Shape 1 | Shape 2|
| ------- | ------- |
| ![Notes1](https://user-images.githubusercontent.com/63608463/154238195-a1f3ceb1-b1b7-4081-9b15-246972e809cc.png) | ![Notes2](https://user-images.githubusercontent.com/63608463/154238252-ded44299-06e9-46fb-819f-ea1f28a4c2a8.png) |

How should the renderer pick the shape in case of mixed curve direction? Both shapes are possible and there is no canonical choice.

**Comment by ahankinson** [comment] 2022-02-16 09:51
I would think shape 2 would be chosen, since it minimizes collisions with the notes?

**Comment by ahankinson** [comment] 2022-02-16 09:54
There is also the `@bezier` attribute on slurs which let you specify complex slur shapes directly.

**Comment by ahankinson** [comment] 2022-02-16 09:55
Or `@bulge` probably would also work?

**Comment by rettinghaus** [comment] 2022-02-16 09:55
`@bezier` would't be sufficient when you're in a dynamic layout environment.

**Comment by rettinghaus** [comment] 2022-02-16 09:56
To use `@bulge` you would have to know if the start point is above or below the note.

**Comment by brdvd** [comment] 2022-02-16 09:57
> I would think shape 2 would be chosen, since it minimizes collisions with the notes?

It is obviously possible to use both shapes without collisions.

![Notes3](https://user-images.githubusercontent.com/63608463/154240275-9f3680dc-800d-4785-9882-7db021acad7a.png)

**Comment by ahankinson** [comment] 2022-02-16 09:58
It seems like `above/below` or `below/above` also wouldn't be sufficient, since that could also change? I don't know if your goal is to exactly reproduce what is written on a printed score, or to produce "good" dynamic rendering? In the case of the former, I would expect things like `@bezier` and `@bulge` to work, since you're reproducing an existing shape. In the case of the latter, `mixed` in `curvedir` would allow the renderer to choose the best direction.

**Comment by brdvd** [comment] 2022-02-16 10:15
I would guess if you encode the curve direction as `mixed` (which is an optional attribute), then you probably have a rough shape in mind that you want to see in the rendering.

Dorico makes this [distinction in shape](https://steinberg.help/dorico/v1/en/dorico/topics/notation_reference/notation_reference_slurs_curvature_direction_r.html) as well.

**Comment by lpugin** [comment] 2022-02-16 10:25
> One suggestion would be to replace curvature_CURVEDIR_mixed by curvature_CURVEDIR_mixed_above_below and curvature_CURVEDIR_mixed_below_above. I am not happy with these long names, so feel free to propose better names.

Maybe we want to keep `curvature_CURVEDIR_mixed` to leave it possible not to have to encode the shape? I think that is what Andrew is wanting not to enforce. 

Also `curvature_CURVEDIR_mixed_below_above` could be simply `curvature_CURVEDIR_below_above`, which implies `mixed` and would make it a bit shorter.

**Comment by ahankinson** [comment] 2022-02-16 10:28
I would be curious to know how Dorico exports their shapes. Looking at the MusicXML output, I see the same bezier functionality, so I'm wondering if it also exports it as a fixed bezier curve?

**Comment by lpugin** [comment] 2022-02-22 15:40
As far as I can tell the shape is not exported.

![image](https://user-images.githubusercontent.com/689412/155166003-da709b99-046d-4c4a-a981-4fa5ac0f217c.png)

Here is the MusicXML snippet for the top staff of measure 1 and 2
```xml
<measure number="1">
   <attributes>
      <divisions>4</divisions>
      <key number="1">
         <fifths>0</fifths>
         <mode>major</mode>
      </key>
      <key number="2">
         <fifths>0</fifths>
         <mode>major</mode>
      </key>
      <time>
         <beats>4</beats>
         <beat-type>4</beat-type>
      </time>
      <staves>2</staves>
      <clef number="1">
         <sign>G</sign>
         <line>2</line>
      </clef>
      <clef number="2">
         <sign>F</sign>
         <line>4</line>
      </clef>
   </attributes>
   <note>
      <pitch>
         <step>D</step>
         <octave>5</octave>
      </pitch>
      <duration>4</duration>
      <voice>1</voice>
      <type>quarter</type>
      <stem>down</stem>
      <staff>1</staff>
      <notations>
         <slur type="start" number="1"/>
      </notations>
   </note>
   <note>
      <pitch>
         <step>C</step>
         <octave>5</octave>
      </pitch>
      <duration>4</duration>
      <voice>1</voice>
      <type>quarter</type>
      <stem>down</stem>
      <staff>1</staff>
   </note>
   <note>
      <pitch>
         <step>A</step>
         <octave>4</octave>
      </pitch>
      <duration>4</duration>
      <voice>1</voice>
      <type>quarter</type>
      <stem>up</stem>
      <staff>1</staff>
   </note>
   <note>
      <pitch>
         <step>G</step>
         <octave>4</octave>
      </pitch>
      <duration>4</duration>
      <voice>1</voice>
      <type>quarter</type>
      <stem>up</stem>
      <staff>1</staff>
      <notations>
         <slur type="stop" number="1"/>
      </notations>
   </note>
   <backup>
      <duration>16</duration>
   </backup>
   <note>
      <rest/>
      <duration>16</duration>
      <voice>2</voice>
      <type>whole</type>
      <staff>2</staff>
   </note>
</measure>
<measure number="2">
   <attributes>
      <divisions>4</divisions>
   </attributes>
   <note>
      <pitch>
         <step>D</step>
         <octave>5</octave>
      </pitch>
      <duration>4</duration>
      <voice>1</voice>
      <type>quarter</type>
      <stem>down</stem>
      <staff>1</staff>
      <notations>
         <slur type="start" number="1"/>
      </notations>
   </note>
   <note>
      <pitch>
         <step>C</step>
         <octave>5</octave>
      </pitch>
      <duration>4</duration>
      <voice>1</voice>
      <type>quarter</type>
      <stem>down</stem>
      <staff>1</staff>
   </note>
   <note>
      <pitch>
         <step>A</step>
         <octave>4</octave>
      </pitch>
      <duration>4</duration>
      <voice>1</voice>
      <type>quarter</type>
      <stem>up</stem>
      <staff>1</staff>
   </note>
   <note>
      <pitch>
         <step>G</step>
         <octave>4</octave>
      </pitch>
      <duration>4</duration>
      <voice>1</voice>
      <type>quarter</type>
      <stem>up</stem>
      <staff>1</staff>
      <notations>
         <slur type="stop" number="1"/>
      </notations>
   </note>
   <backup>
      <duration>16</duration>
   </backup>
   <note>
      <rest/>
      <duration>16</duration>
      <voice>2</voice>
      <type>whole</type>
      <staff>2</staff>
   </note>
</measure>
```

This is what I can see when reimporting into MuseScore (or reimporting back into Dorico)

![image](https://user-images.githubusercontent.com/689412/155166214-22f8da88-15ba-4999-b776-830822281ee9.png)

**Comment by lpugin** [comment] 2022-03-09 07:04
I am going to make a PR about this. Please let me know if there are any remaining doubts about it.

**Comment by brdvd** [comment] 2022-03-10 08:08
@lpugin Thank you! No doubts from my side, I liked the last suggestion:
> Maybe we want to keep `curvature_CURVEDIR_mixed` to leave it possible not to have to encode the shape? I think that is what Andrew is wanting not to enforce.
> 
> Also `curvature_CURVEDIR_mixed_below_above` could be simply `curvature_CURVEDIR_below_above`, which implies `mixed` and would make it a bit shorter.

**Comment by musicEnfanthen** [comment] 2022-10-01 14:18
Discussion at MEI Developer Workshop Berlin lead to an alternative approach for modelling s-slurs. Will be introduced in another PR. Closing this PR.

**Closed as completed by musicEnfanthen** 2022-10-01 14:18 UTC
