### ISSUE TITLE
Guidelines: handle xml comments differently

### ISSUE THREAD

**Issue by bwbohl** [music-encoding/music-encoding#775] opened 2021-02-25 13:18 UTC
As mentioned in #762, XML comments in the guidelines are just passed through to the HTML result. This basically is not bad for e.g. the development version of the guidelines but the graphical layout should be rendered more drastically; at the moment the only traces of a comment in the HTML are `<!--`and `-->`, e.g.:

![Screenshot 2021-02-25 at 14 10 39](https://user-images.githubusercontent.com/2430401/109158148-45beab00-7773-11eb-8c13-9ba06d359c09.png)

In the released version the comments should definitely be removed, though.

**Comment by kepper** [comment] 2021-03-25 23:35
I cannot reproduce this behavior, and /dev seems fine for me. I remember having seen this, and I'm not aware of any changes, but I think it's safe to close this for now?

**Comment by kepper** [comment] 2021-03-26 14:06
it seems @martha-thomae has taken out the comments, but having comments in the dev version is actually a helpful feature, so I'll explore a bit more and see what we can do…

**Comment by kepper** [comment] 2021-04-29 10:23
I just double-checked. Comments in the docs code are definitely possible, and don't leave unwanted traces in the generated web output. I therefore think we have the expected behavior and this issue can be safely closed without further action.

**Closed as completed** 2021-04-29 12:38 UTC
Labels: Priority: Medium, Type: Bug, Status: Won't Fix, Component: Utils
