### ISSUE TITLE
Byzantine Notation Support

### ISSUE THREAD

**Issue by t-bullock** [music-encoding/music-encoding#707] opened 2020-09-08 18:27 UTC
Are there any plans to support Byzantine Notation (New Method, 1814)?

**Comment by bwbohl** [comment] 2020-10-02 13:41
@t-bullock at the moment I'm not aware of any advances in that direction. @annplaksin are you aware of any notions? How close is that to your ottoman notation, are there any overlaps?
But of course, if you're able to provide the musicological expertise we could at least assist you in the modelling aspects ;-)

**Comment by annplaksin** [comment] 2020-10-05 07:50
Yes, Byzantine Notation is used in Ottoman sources too. So we're thinking about preparing a proposal for its support in MEI, but it's not our highest priority yet.
@t-bullock I'm repeating the invitation: If you're able to provide some expertise, you are happily invited to join our task. We already have a turkish-music channel at the [MEI Slack](https://music-encoding.org/community/community-contacts.html)

**Comment by nsiklafidis** [comment] 2021-03-29 18:02
@bwbohl , @annplaksin @t-bullock I have a master in Byzantine Musicology at the Aristotle University of Thessaloniki and a good knowledge on xml. I would like to contribute for the MEI schema. The signs (notes) for the Byzantine Music in unicode system are between 1D000-1D0FF (246 signs). The problem is that we need more signs to write in varius notational types e.g. for the Greek chant repertories belonging to the 3rd-21st centuries A.D. It is necessary to use the unicode system? Can we create a font for the contact with the MEI schema? 
Please help us about the modelling aspects so we can start this task.
Thank you!

**Comment by bwbohl** [comment] 2021-04-10 09:51
Welcome @nsiklafidis , and sorry for my late reply!!
It's great to hear hat you are seeking yet for another repertoire to be encoded in MEI. First MEI is absolutely unconnected to the unicode code blocks. What MEI does is capture the semantics of musical symbols. To get a first glimpse of how MEI works in generals I'd recommend the tutorial on the websit, e.g. https://music-encoding.org/tutorials/101-quickstart.html
If you want to see other notation systems covered please have a look at the customisations for Neues or Mensural notation.
If MEI tags do not cover your needs a first step would be to make a logical model of your needs, e.g. for Common Western Notation this might be something like:

* Notation
  * staff
    * measure
      * multiple voices

As you might not want to transliterate your notation systems into CWN, but instead capture the original semantics you might have to introduce new elements that reflect the semantics of your notation system.
If you have any questions or need of assistance please feel free to contact me ;-)

**Comment by nsiklafidis** [comment] 2021-04-10 12:10
@bwbohl thank you for your answer!!
1. I saw that with the code `<note pname="c" oct="4" dur="4"/>` we render the musical note C (Do).
2. Do you use a font to render this? I create an example for one byzantine musical note here: https://nsiklafidis.github.io/ but I use html, css and a font. Can you give me an example something like that for the musical note C?

**Comment by bwbohl** [comment] 2021-04-12 08:27
1. The Tutorials render the notation using Verovio (https://www.verovio.org/index.xhtml).
2. What is the meaning of the ions character? That would be the first question to answer for all symbols, probably more than those e.g. on https://decodeunicode.org/en/u+1D000?

**Comment by bwbohl** [comment] 2021-04-12 08:29
Do you know whether the https://decodeunicode.org/en/u+1D000 symbols are covered in the Standard Music Font Layout (SMuFL https://www.smufl.org)?

**Comment by rettinghaus** [comment] 2021-04-12 08:33
@bwbohl Daniel doesn't want to duplicate those, see https://github.com/w3c/smufl/issues/45.

**Comment by bwbohl** [comment] 2021-04-12 15:01
> @bwbohl Daniel doesn't want to duplicate those, see [w3c/smufl#45](https://github.com/w3c/smufl/issues/45).

thanks for adding, missed that one as I didn't look in the closed issues :-/

**Comment by nsiklafidis** [comment] 2021-04-12 16:54
@bwbohl @rettinghaus 
Thank you for your answers!
I agree, we have a unicode system for Byzantine Music.
So the only way to render Byzantine Music in MEI schema is to write with this unicode system?

**Comment by rettinghaus** [comment] 2021-04-16 07:31
@nsiklafidis Yes, to render the music you should rely on the unicode system. However, it is unclear to me how this music should be encoded in MEI as I don't know enough about this kind of music.

**Comment by ahankinson** [comment] 2021-06-16 07:44
I'm moving this to Discussions.

**Closed as completed** 2021-06-16 07:44 UTC
Labels: Component: Core Schema, Priority: Low, Type: Support Request
