### ISSUE TITLE
Partial layers

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#371] opened 2016-12-31 22:43 UTC
Is there a concept of a "partial layer" in MEI?

Consider this example:

<img width="404" alt="screen shot 2016-12-31 at 13 59 31" src="https://cloud.githubusercontent.com/assets/3487289/21579397/c6377898-cf61-11e6-964f-fcce91961836.png">

This is rendered with verovio.  Notice that the top tie at the end of measure 13 is pointing downwards, but in m. 15, the analogous tie is pointing upwards.  The downward pointing slur is due to the chord being encoded in the second layer, while there is a `<space>` filling in the rest of the first layer.  The layout algorithm then says that all ties must point downwards if the notes are in the second layer in a two-layer context.

If the second layer is instead filled in with a `<space>` and the chord is placed in the first layer, then the visual syntax is disrupted even more:

<img width="405" alt="screen shot 2016-12-31 at 14 10 46" src="https://cloud.githubusercontent.com/assets/3487289/21579422/0d37c012-cf63-11e6-8447-792ecdb921ca.png">

In this case the ties all point in the opposite direction because they are in layer 1 in a two-layer context.  In addition the stem is in the opposite direction due to the same reason.

It would be semantically more proper to indicate that the last two quarter notes of measure 13 are to be interpreted as a region of music containing only a single layer, rather than two layers.  Should the presence of a`<space>` in a layer automatically control this behavior?  I.e., whenever there is a space in a layer, that layer should be considered inactive when laying out the notes from other layers.  If there are two layers and one has a space, then the other layer would be interpreted as the  only layer.  Alternatively, there could be an attribute for `<space>` which indicates what the layer-based layout behavior should be: either the current interpretation in verovio, or the newly proposed one.

Humdrum can encode partial layers.  Here is how the first case above is encoded (with the chord in question in the second layer and an explicit `<space>` in layer 1:

```
**kern
*clefG2
=13-
*^
2dd         4b]
.           4a)
2ryy        4r
.           [4b [4dd [4aa
*v          *v
=14
4b] 4dd] 4aa]
4cc 4ee 4gg
8r
16r
16gLK
8.dd
16ffJk
=15
```

The chord is encoded in the second layer, and there is an invisible rest in the first layer.

Here is an example of encoding the chord in the first layer, but keeping a complete second layer (this is the source for the second notation example above):

```
**kern
*clefG2
=13-
*^
2dd             4b]
.               4a)
4r              2ryy
[4b [4dd [4aa   .       
*v              *v
=14
4b] 4dd] 4aa]
4cc 4ee 4gg
8r
16r
16gLK
8.dd
16ffJk
=15
```

A third way of representing in Humdrum involves a partial layer, and is semantically superior for this sort of case:

```xml
**kern
*clefG2
=13-
*^
2dd             4b]
.               4a)
*v              *v
4r
[4b [4dd [4aa
=14
4b] 4dd] 4aa]
4cc 4ee 4gg
8r
16r
16gLK
8.dd
16ffJk
=15
```

This does not seem to be representable in MEI, as it is indistinguishable from the previous encoding examples when expressed in MEI:  in my conversion from Humdrum to MEI, I use `<space>` for both implicit cases where there is a partial layer in the Humdrum data, or an explicit case where there is an invisible rest filling in a layer in the Humdrum data.

(clef changes in such situations will also complicate matters).

**Comment by pe-ro** [comment] 2017-01-05 22:58
@craigsapp, How does Verovio render your first example if the 2nd layer of the 1st measure contains only the first 2 notes without a following `<space>`?  In other words, does Verovio think there are 2 layers throughout the entire measure?

**Comment by craigsapp** [comment] 2017-01-21 20:52
> without a following ? 

There seems to be some text before the "?" which is in angle brackets, but I cannot see it because the text is not escaped with backticks.

>  In other words, does Verovio think there are 2 layers throughout the entire measure?

Yes because I told it there were two layers all of the way through the measure.  In the first case the there is an invisible half rests, which maps to a `<space>`, for the second half of the first layer:

```
**kern
*clefG2
=13-
*^
2dd         4b]
.           4a)
2ryy        4r
.           [4b [4dd [4aa
*v          *v
=14
4b] 4dd] 4aa]
4cc 4ee 4gg
8r
16r
16gLK
8.dd
16ffJk
=15
```

```bash
$ ./verovio input.krn
```

<img width="793" alt="screen shot 2017-01-21 at 12 51 22" src="https://cloud.githubusercontent.com/assets/3487289/22177704/63dcdb84-dfd8-11e6-9569-acac05bd21ed.png">


```bash
$ ./verovio input.krn -t mei --all-pages --no-layout
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt>
                <date>2017-01-21 12:49:09</date>
            </pubStmt>
        </fileDesc>
        <encodingDesc>
            <projectDesc>
                <p>Transcoded from Humdrum with Verovio version 0.9.14-dev-ea2b196</p>
            </projectDesc>
        </encodingDesc>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef xml:id="scoredef-000000126564231">
                        <staffGrp xml:id="m-000000149901250">
                            <staffDef xml:id="staffdef-000000177242454" clef.shape="G" clef.line="2" n="1" lines="5" />
                        </staffGrp>
                    </scoreDef>
                    <section xml:id="section-000000092861680">
                        <measure xml:id="measure-L3" n="13">
                            <staff xml:id="staff-L3F1" n="1">
                                <layer xml:id="layer-L3F1" n="1">
                                    <note xml:id="note-L5F1" dur="2" oct="5" pname="d" accid.ges="n" />
                                    <space xml:id="space-L7F1" dur="2" />
                                </layer>
                                <layer xml:id="layer-L5F2" n="2">
                                    <note xml:id="note-L5F2" dur="4" oct="4" pname="b" accid.ges="n" />
                                    <note xml:id="note-L6F2" dur="4" oct="4" pname="a" accid.ges="n" />
                                    <rest xml:id="rest-L7F2" dur="4" />
                                    <chord xml:id="chord-L8F2" dur="4">
                                        <note xml:id="note-L8F2S1" oct="4" pname="b" accid.ges="n" />
                                        <note xml:id="note-L8F2S2" oct="5" pname="d" accid.ges="n" />
                                        <note xml:id="note-L8F2S3" oct="5" pname="a" accid.ges="n" />
                                    </chord>
                                </layer>
                            </staff>
                            <tie xml:id="tie-000000207020196" startid="#note-L8F2S1" endid="#note-L11F1S1" />
                            <tie xml:id="tie-000000076063584" startid="#note-L8F2S2" endid="#note-L11F1S2" />
                            <tie xml:id="tie-000000192582857" startid="#note-L8F2S3" endid="#note-L11F1S3" />
                        </measure>
                        <measure xml:id="measure-L10" n="14">
                            <staff xml:id="staff-L10F1" n="1">
                                <layer xml:id="layer-L10F1" n="1">
                                    <chord xml:id="chord-L11F1" dur="4">
                                        <note xml:id="note-L11F1S1" oct="4" pname="b" accid.ges="n" />
                                        <note xml:id="note-L11F1S2" oct="5" pname="d" accid.ges="n" />
                                        <note xml:id="note-L11F1S3" oct="5" pname="a" accid.ges="n" />
                                    </chord>
                                    <chord xml:id="chord-L12F1" dur="4">
                                        <note xml:id="note-L12F1S1" oct="5" pname="c" accid.ges="n" />
                                        <note xml:id="note-L12F1S2" oct="5" pname="e" accid.ges="n" />
                                        <note xml:id="note-L12F1S3" oct="5" pname="g" accid.ges="n" />
                                    </chord>
                                    <rest xml:id="rest-L13F1" dur="8" />
                                    <rest xml:id="rest-L14F1" dur="16" />
                                    <beam xml:id="beam-000000003776832">
                                        <note xml:id="note-L15F1" dur="16" oct="4" pname="g" accid.ges="n" />
                                        <note xml:id="note-L16F1" dots="1" dur="8" oct="5" pname="d" accid.ges="n" />
                                        <note xml:id="note-L17F1" dur="16" oct="5" pname="f" accid.ges="n" />
                                    </beam>
                                </layer>
                            </staff>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

**Comment by craigsapp** [comment] 2017-01-21 20:59
Here is MEI data for the second example, where the `<space>` is in the second layer:

```
**kern
*clefG2
=13-
*^
2dd	4b]
.	4a)
4r	2ryy
[4b [4dd [4aa	.
*v	*v
=14
4b] 4dd] 4aa]
4cc 4ee 4gg
8r
16r
16gLK
8.dd
16ffJk
=15
```

```bash
$ ./verovio input2.krn
```

<img width="793" alt="screen shot 2017-01-21 at 12 54 32" src="https://cloud.githubusercontent.com/assets/3487289/22177721/e267ea52-dfd8-11e6-95fc-ad06f2053d26.png">

Verovio is happier with this encoding since the ties do not switch layer numbers (but it gets them correctly linked in both cases).

MEI data:

```bash
$ ./verovio input2.krn -t mei --all-pages --no-layout
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt>
                <date>2017-01-21 12:56:00</date>
            </pubStmt>
        </fileDesc>
        <encodingDesc>
            <projectDesc>
                <p>Transcoded from Humdrum with Verovio version 0.9.14-dev-ea2b196</p>
            </projectDesc>
        </encodingDesc>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef xml:id="scoredef-000000020307646">
                        <staffGrp xml:id="m-000000007166014">
                            <staffDef xml:id="staffdef-000000180119788" clef.shape="G" clef.line="2" n="1" lines="5" />
                        </staffGrp>
                    </scoreDef>
                    <section xml:id="section-000000091192136">
                        <measure xml:id="measure-L3" n="13">
                            <staff xml:id="staff-L3F1" n="1">
                                <layer xml:id="layer-L3F1" n="1">
                                    <note xml:id="note-L5F1" dur="2" oct="5" pname="d" accid.ges="n" />
                                    <rest xml:id="rest-L7F1" dur="4" />
                                    <chord xml:id="chord-L8F1" dur="4">
                                        <note xml:id="note-L8F1S1" oct="4" pname="b" accid.ges="n" />
                                        <note xml:id="note-L8F1S2" oct="5" pname="d" accid.ges="n" />
                                        <note xml:id="note-L8F1S3" oct="5" pname="a" accid.ges="n" />
                                    </chord>
                                </layer>
                                <layer xml:id="layer-L5F2" n="2">
                                    <note xml:id="note-L5F2" dur="4" oct="4" pname="b" accid.ges="n" />
                                    <note xml:id="note-L6F2" dur="4" oct="4" pname="a" accid.ges="n" />
                                    <space xml:id="space-L7F2" dur="2" />
                                </layer>
                            </staff>
                            <tie xml:id="tie-000000060210795" startid="#note-L8F1S1" endid="#note-L11F1S1" />
                            <tie xml:id="tie-000000190520593" startid="#note-L8F1S2" endid="#note-L11F1S2" />
                            <tie xml:id="tie-000000195465793" startid="#note-L8F1S3" endid="#note-L11F1S3" />
                        </measure>
                        <measure xml:id="measure-L10" n="14">
                            <staff xml:id="staff-L10F1" n="1">
                                <layer xml:id="layer-L10F1" n="1">
                                    <chord xml:id="chord-L11F1" dur="4">
                                        <note xml:id="note-L11F1S1" oct="4" pname="b" accid.ges="n" />
                                        <note xml:id="note-L11F1S2" oct="5" pname="d" accid.ges="n" />
                                        <note xml:id="note-L11F1S3" oct="5" pname="a" accid.ges="n" />
                                    </chord>
                                    <chord xml:id="chord-L12F1" dur="4">
                                        <note xml:id="note-L12F1S1" oct="5" pname="c" accid.ges="n" />
                                        <note xml:id="note-L12F1S2" oct="5" pname="e" accid.ges="n" />
                                        <note xml:id="note-L12F1S3" oct="5" pname="g" accid.ges="n" />
                                    </chord>
                                    <rest xml:id="rest-L13F1" dur="8" />
                                    <rest xml:id="rest-L14F1" dur="16" />
                                    <beam xml:id="beam-000000082178823">
                                        <note xml:id="note-L15F1" dur="16" oct="4" pname="g" accid.ges="n" />
                                        <note xml:id="note-L16F1" dots="1" dur="8" oct="5" pname="d" accid.ges="n" />
                                        <note xml:id="note-L17F1" dur="16" oct="5" pname="f" accid.ges="n" />
                                    </beam>
                                </layer>
                            </staff>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

**Comment by craigsapp** [comment] 2017-01-21 21:15
I am thinking that this should be the responsibility of the renderer (i.e., verovio) to auto-detect the presence of certain types of `<space>`s in layers in order to do automatic layout (stem directions, articulation placement, slur/tie directions,  etc.), but there should be guidance in the MEI documentation for these sorts of cases.

Here is a correct rendering in verovio generated by splitting the measure into two parts with an invisible barline.  This simulates partial layers since the first measure has two layers, and the fake second measure has one layer.  Notice that the rest in the first measure is not in its correct vertical position as well.

```
**kern
*clefG2
=13-
*^
2dd	4b]
.	4a)
*v	*v
=-
4r
[4b [4dd [4aa
=14
4b] 4dd] 4aa]
4cc 4ee 4gg
8r
16r
16gLK
8.dd
16ffJk
=15
```

```bash
$ ./verovio input3.krn
```

<img width="808" alt="screen shot 2017-01-21 at 13 02 39" src="https://cloud.githubusercontent.com/assets/3487289/22177775/e87e5722-dfd9-11e6-9d21-63b952a192bd.png">

```bash
$ ./verovio input3.krn -t mei --all-pages --no-layout
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt>
                <date>2017-01-21 13:04:04</date>
            </pubStmt>
        </fileDesc>
        <encodingDesc>
            <projectDesc>
                <p>Transcoded from Humdrum with Verovio version 0.9.14-dev-ea2b196</p>
            </projectDesc>
        </encodingDesc>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef xml:id="scoredef-000000017443730">
                        <staffGrp xml:id="m-000000172435120">
                            <staffDef xml:id="staffdef-000000087890297" clef.shape="G" clef.line="2" n="1" lines="5" />
                        </staffGrp>
                    </scoreDef>
                    <section xml:id="section-000000086091043">
                        <measure xml:id="measure-L3" n="13" right="invis">
                            <staff xml:id="staff-L3F1" n="1">
                                <layer xml:id="layer-L3F1" n="1">
                                    <note xml:id="note-L5F1" dur="2" oct="5" pname="d" accid.ges="n" />
                                </layer>
                                <layer xml:id="layer-L5F2" n="2">
                                    <note xml:id="note-L5F2" dur="4" oct="4" pname="b" accid.ges="n" />
                                    <note xml:id="note-L6F2" dur="4" oct="4" pname="a" accid.ges="n" />
                                </layer>
                            </staff>
                        </measure>
                        <measure xml:id="measure-L8">
                            <staff xml:id="staff-L8F1" n="1">
                                <layer xml:id="layer-L8F1" n="1">
                                    <rest xml:id="rest-L9F1" dur="4" />
                                    <chord xml:id="chord-L10F1" dur="4">
                                        <note xml:id="note-L10F1S1" oct="4" pname="b" accid.ges="n" />
                                        <note xml:id="note-L10F1S2" oct="5" pname="d" accid.ges="n" />
                                        <note xml:id="note-L10F1S3" oct="5" pname="a" accid.ges="n" />
                                    </chord>
                                </layer>
                            </staff>
                            <tie xml:id="tie-000000146325024" startid="#note-L10F1S1" endid="#note-L12F1S1" />
                            <tie xml:id="tie-000000099679860" startid="#note-L10F1S2" endid="#note-L12F1S2" />
                            <tie xml:id="tie-000000212379524" startid="#note-L10F1S3" endid="#note-L12F1S3" />
                        </measure>
                        <measure xml:id="measure-L11" n="14">
                            <staff xml:id="staff-L11F1" n="1">
                                <layer xml:id="layer-L11F1" n="1">
                                    <chord xml:id="chord-L12F1" dur="4">
                                        <note xml:id="note-L12F1S1" oct="4" pname="b" accid.ges="n" />
                                        <note xml:id="note-L12F1S2" oct="5" pname="d" accid.ges="n" />
                                        <note xml:id="note-L12F1S3" oct="5" pname="a" accid.ges="n" />
                                    </chord>
                                    <chord xml:id="chord-L13F1" dur="4">
                                        <note xml:id="note-L13F1S1" oct="5" pname="c" accid.ges="n" />
                                        <note xml:id="note-L13F1S2" oct="5" pname="e" accid.ges="n" />
                                        <note xml:id="note-L13F1S3" oct="5" pname="g" accid.ges="n" />
                                    </chord>
                                    <rest xml:id="rest-L14F1" dur="8" />
                                    <rest xml:id="rest-L15F1" dur="16" />
                                    <beam xml:id="beam-000000016759324">
                                        <note xml:id="note-L16F1" dur="16" oct="4" pname="g" accid.ges="n" />
                                        <note xml:id="note-L17F1" dots="1" dur="8" oct="5" pname="d" accid.ges="n" />
                                        <note xml:id="note-L18F1" dur="16" oct="5" pname="f" accid.ges="n" />
                                    </beam>
                                </layer>
                            </staff>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

This is a hack, so not good to put in the data.  But this is a hint on how to do an easy implementation in the renderer to simulate partial layers.

**Comment by craigsapp** [comment] 2017-01-21 21:29
And here is an example where I manually set `@stem.dir="down"` on the first chord, and the bottom tie has `@curvedir="down"` to get the correct rendering in veorvio (both of which I should not have to do if concept of partial layers is implemented):

```
**kern
*clefG2
=13-
*^
2dd	4b]
.	4a)
4r	.
[<4b\ [4dd\ [4aa\	.
*v	*v
=14
4b] 4dd] 4aa]
4cc 4ee 4gg
8r
16r
16gLK
8.dd
16ffJk
=15
*-
!!!RDF**kern: < = below
```

```bash
$ ./verovio input4.krn
```

<img width="798" alt="screen shot 2017-01-21 at 13 20 55" src="https://cloud.githubusercontent.com/assets/3487289/22177882/754103ec-dfdc-11e6-8019-5338e24bee44.png">

Although the quarter-note rest would still also have to be corrected.

```bash
$ ./verovio input4.krn -t mei --all-pages --no-layout
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt>
                <date>2017-01-21 13:21:58</date>
            </pubStmt>
        </fileDesc>
        <encodingDesc>
            <projectDesc>
                <p>Transcoded from Humdrum with Verovio version 0.9.14-dev-ea2b196</p>
            </projectDesc>
        </encodingDesc>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef xml:id="scoredef-000000144197167">
                        <staffGrp xml:id="m-000000070626746">
                            <staffDef xml:id="staffdef-000000109516728" clef.shape="G" clef.line="2" n="1" lines="5" />
                        </staffGrp>
                    </scoreDef>
                    <section xml:id="section-000000120915951">
                        <measure xml:id="measure-L3" n="13">
                            <staff xml:id="staff-L3F1" n="1">
                                <layer xml:id="layer-L3F1" n="1">
                                    <note xml:id="note-L5F1" dur="2" oct="5" pname="d" accid.ges="n" />
                                    <rest xml:id="rest-L7F1" dur="4" />
                                    <chord xml:id="chord-L8F1" dur="4" stem.dir="down">
                                        <note xml:id="note-L8F1S1" oct="4" pname="b" accid.ges="n" />
                                        <note xml:id="note-L8F1S2" oct="5" pname="d" accid.ges="n" />
                                        <note xml:id="note-L8F1S3" oct="5" pname="a" accid.ges="n" />
                                    </chord>
                                </layer>
                                <layer xml:id="layer-L5F2" n="2">
                                    <note xml:id="note-L5F2" dur="4" oct="4" pname="b" accid.ges="n" />
                                    <note xml:id="note-L6F2" dur="4" oct="4" pname="a" accid.ges="n" />
                                    <space xml:id="space-000000126706195" dur="2" />
                                </layer>
                            </staff>
                            <tie xml:id="tie-000000067994707" startid="#note-L8F1S1" endid="#note-L11F1S1" curvedir="below" />
                            <tie xml:id="tie-000000166164642" startid="#note-L8F1S2" endid="#note-L11F1S2" />
                            <tie xml:id="tie-000000175044170" startid="#note-L8F1S3" endid="#note-L11F1S3" />
                        </measure>
                        <measure xml:id="measure-L10" n="14">
                            <staff xml:id="staff-L10F1" n="1">
                                <layer xml:id="layer-L10F1" n="1">
                                    <chord xml:id="chord-L11F1" dur="4">
                                        <note xml:id="note-L11F1S1" oct="4" pname="b" accid.ges="n" />
                                        <note xml:id="note-L11F1S2" oct="5" pname="d" accid.ges="n" />
                                        <note xml:id="note-L11F1S3" oct="5" pname="a" accid.ges="n" />
                                    </chord>
                                    <chord xml:id="chord-L12F1" dur="4">
                                        <note xml:id="note-L12F1S1" oct="5" pname="c" accid.ges="n" />
                                        <note xml:id="note-L12F1S2" oct="5" pname="e" accid.ges="n" />
                                        <note xml:id="note-L12F1S3" oct="5" pname="g" accid.ges="n" />
                                    </chord>
                                    <rest xml:id="rest-L13F1" dur="8" />
                                    <rest xml:id="rest-L14F1" dur="16" />
                                    <beam xml:id="beam-000000066925248">
                                        <note xml:id="note-L15F1" dur="16" oct="4" pname="g" accid.ges="n" />
                                        <note xml:id="note-L16F1" dots="1" dur="8" oct="5" pname="d" accid.ges="n" />
                                        <note xml:id="note-L17F1" dur="16" oct="5" pname="f" accid.ges="n" />
                                    </beam>
                                </layer>
                            </staff>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

**Comment by craigsapp** [comment] 2017-01-22 00:15
See also https://github.com/rism-ch/verovio/issues/262

**Comment by bwbohl** [comment] 2017-01-30 10:03
We encountered similar "logical" problems when encoding the Freischütz score, especially on the woodwinds. Most of the times we had 'divisi' (indicated by the stem directions) with all their respective notes encoded on the respective layers. Then sometimes a chord was written instead (Which is kind of hard – impossible – to play on a wind instrument ;-) Do we ended up encoding the chord on layer-1 while a space on layer-2 would carry ```@corresp``` to point to that specific chord.

We did this, because we wanted to capture the specific graphical features of the score. When intending to capture the logical stream of the piece I might switch to ```<part>``` instead of ```<score>```in the future though.

The source-specific rendering of the score should then be captured by other features.

**Comment by craigsapp** [comment] 2017-01-30 16:27
> When intending to capture the logical stream of the piece I might switch to `<part>` instead of `<score>` in the future though.

This is how it is done with MuseData: parts are encoded first, and then a score is "compiled" from the parts.  During the compiling process, different types of scores can be generated, such as a "conducting score" layout where the parts maintain separate stems, or a "study/condensed score" layout where the stems are merged when the rhythms are the same:

<img width="1124" alt="screen shot 2017-01-30 at 08 18 47" src="https://cloud.githubusercontent.com/assets/3487289/22431028/f889f814-e6c4-11e6-9421-a6bb442ce5b7.png">

Also, when doing OCR on an orchestral work.  It is more efficient to process the parts individually instead of as a full-score.

**Comment by pe-ro** [comment] 2017-01-30 16:46
@craigsapp already hit on one approach:
> I am thinking that this should be the responsibility of the renderer (i.e., verovio) to auto-detect the presence of certain types of <space>s in layers in order to do automatic layout (stem directions, articulation placement, slur/tie directions, etc.), but there should be guidance in the MEI documentation for these sorts of cases.

Following this line of thinking, it's up to Verovio to manage the interplay between layers.  I'm fine with this since it doesn't require any changes to MEI. 😀 

Another possibility is to introduce a new element that signals the splitting of a layer into sub-layer streams.  I'm calling these sub-layer components `<pLayer>` -- "partial layer".  (Read as "player", however, the name also fits where there's an actual _divisi_.  I'm trying to avoid the name "layerPart" since that's the name for the class that represents a subset of things that can occur within a layer.)

Using this element, m. 13 of Craig's first example could be encoded --
```
<measure xml:id="measure-L3" n="13">
  <staff xml:id="staff-L3F1" n="1">
    <layer xml:id="layer-L3F1" n="1">
      <pLayers>
        <pLayer>
          <note xml:id="note-L5F1" dur="2" oct="5" pname="d" accid.ges="n"/>
        </pLayer>
        <pLayer>
          <note xml:id="note-L5F2" dur="4" oct="4" pname="b" accid.ges="n"/>
          <note xml:id="note-L6F2" dur="4" oct="4" pname="a" accid.ges="n"/>
        </pLayer>
      </pLayers>
      <rest xml:id="rest-L7F2" dur="4"/>
      <chord xml:id="chord-L8F2" dur="4">
        <note xml:id="note-L8F2S1" oct="4" pname="b" accid.ges="n"/>
        <note xml:id="note-L8F2S2" oct="5" pname="d" accid.ges="n"/>
        <note xml:id="note-L8F2S3" oct="5" pname="a" accid.ges="n"/>
      </chord>
    </layer>
  </staff>
  <tie xml:id="tie-000000207020196" startid="#note-L8F2S1" endid="#note-L11F1S1"/>
  <tie xml:id="tie-000000076063584" startid="#note-L8F2S2" endid="#note-L11F1S2"/>
  <tie xml:id="tie-000000192582857" startid="#note-L8F2S3" endid="#note-L11F1S3"/>
</measure>
```
The `<pLayers>` element signals the splitting of the layer into two or more parallel segments, each represented by a `<pLayer>` element.  The content model of `<pLayer>` is the same as `<layer>`, i.e., notes, rests, chords, etc.  Closing the `<pLayers>` element indicates a return to a single, unified layer.

Partial layers are required to be co-extensive; that is, equal in duration, but, like layers, it's not necessary to "pad out" any silence/space at the end.  So, if the 2nd "voice" had a space on beat 2, this would be ok --
```
<pLayer>
  <note xml:id="note-L5F2" dur="4" oct="4" pname="b" accid.ges="n"/>
</pLayer>
```
but if there were a space on beat 1, it would have to be accounted for --
```
<pLayer>
  <space dur="4"/>
  <note xml:id="note-L6F2" dur="4" oct="4" pname="a" accid.ges="n"/>
</pLayer>
```
Slurs, ties, and other things that cross sub-layer boundaries will continue to work without modification, I believe.  More investigation may be necessary on this front, though.

This solution has the (perhaps) negative effects of "deepening" the hierarchy and requiring complex decisions about when to use  `<pLayers>` vs. when to use just `<layer>`.

**Comment by pe-ro** [comment] 2017-01-30 17:02
> This is how it is done with MuseData: ...

MEI also offers the possibility of encoding a score as a set of parts --
```
<mdiv>
  <parts>
    <part/>
    <part/>
  </parts>
</mdiv>
```
This is fine as long as the goal is printed editions (diplomatic or not).  But it's not easy to capture source differences using this approach.  This method also places the burden on the rendering software to determine which of the 3 output possibilities is "correct".  MEI attempts to encode explicitly which one is present in the source material.

Can't choose which approach to pursue?  Use them both! --
```
<mdiv>
  <score/>
  <parts>
    <part/>
    <part/>
  </parts>
</mdiv>
```

**Comment by pe-ro** [comment] 2017-09-07 06:12
Another possible approach is to add an attribute to `<space>` to indicate that the layer containing it can be ignored for layout purposes.  For example --
```
<staff n="1">
  <layer n="1">
    <note dur="2" oct="5" pname="d" accid.ges="n"/>
    <space dur="2" ignorable="true"/>
  </layer>
  <layer n="2">
    <note dur="4" oct="4" pname="b" accid.ges="n"/>
    <note dur="4" oct="4" pname="a" accid.ges="n"/>
    <rest dur="4"/>
    <chord dur="4">
      <note oct="4" pname="b" accid.ges="n"/>
      <note oct="5" pname="d" accid.ges="n"/>
      <note oct="5" pname="a" accid.ges="n"/>
    </chord>
  </layer>
</staff>
```
the `@ignorable` attribute means that layer 2 is effectively the only layer in the 2nd half of the measure.  Can Verovio handle that?

**Comment by lpugin** [comment] 2017-09-07 07:13
There was an issue with tied chords which I just fix. The first example given in this thread is now rendered as.

![image](https://user-images.githubusercontent.com/689412/30150632-6d97b08a-93ac-11e7-9dcb-a84903b3d703.png)

`<space>` elements are ignored by default, which I think should be the expected behaviour and I am not sure we need an additional attribute.

**Comment by kepper** [comment] 2017-09-07 10:54
I must say that Perry's suggestion of pLayers is tempting. It seems like it's opening the door to madness, and will surely increase complexity of processing significantly – not only for rendering, but also for analysis and so on. At the same time, it remedies the problem if identifying consistent layers throughout a complete measure when the source only has separate layers for parts of that measure. In essence, "illogical" spaces would go (mostly?) away, which are just a way to push things to the right place, but have no logical meaning or real counterpart in the source.

I feel like we should discuss this approach some more. At this point, I can't say where I stand…

**Comment by pe-ro** [comment] 2017-09-07 15:24
I was proposing the additional attribute on `<space>` in order to avoid following through on my earlier suggestion of `<pLayer>`.  😀 

Now that @lpugin has changed Verovio to ignore the portion of a layer containing space, is this still an issue?  How about if we close this issue and open another one if/when `<pLayer>` becomes necessary?

**Comment by lpugin** [comment] 2017-09-07 17:03
Fine with me

**Closed as completed** 2017-09-13 19:23 UTC
Labels: Component: Core Schema, Priority: Medium, Type: Feature Request

**Comment by ahankinson** [comment] 2017-09-13 20:57
A note why this was closed would be helpful.

**Comment by pe-ro** [comment] 2017-09-13 21:09
This issue was closed because Verovio will take care of partial/incomplete layers by default.

**Comment by ahankinson** [comment] 2017-09-13 21:41
OK.
