### ISSUE TITLE
@staff="0" or @staff="all" for <dir> and <harm>, etc.

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#435] opened 2017-05-21 06:45 UTC
It would be useful to have a way of attaching things like text directions and harmony (floating elements)  to the system rather than a staff.  Is this possible in MEI?

For example `<tempo>` is more properly attached to the system rather than to the top staff in a system (or to the top staff in a beamed group), since it applies to all staves rather than only the top staff.

This would be useful in particular when extracting parts from a full score.  Elements labeled `@staff="0"` or `@staff="all"` or something similar would also be extracted from the full score into the part.  If `@place="above"` then the item would be placed above the system, and `@place="below"` would place the item below the system.

**Comment by pe-ro** [comment] 2017-05-21 13:16
The problem with the value "all" is that it can be interpreted 2 different ways -- 

1. it refers to *each and every staff in the system* or 
2. it refers to *the system*.

In the first case, `@staff="all" @place="above"` means "the tempo marking appears above every staff in the system".  In the second, it means "the tempo marking applies to every staff, but it only appears above the system".

We can use "all" and "system", respectively to make this distinction.  Or we can provide only "system" and continue to force the use of a list of staff numbers when the user means "each and every".

Another issue with adding "system" is that it will require making `@staff` accept either a number or the string "system".  @lpugin would just love this, as it will require one more change to libmei.

**Comment by rettinghaus** [comment] 2017-05-21 13:50
Not only @lpugin would love that. It wouldn't really solve problems, but bring up new ones. Think of this: in bigger scores it is usual to put a tempo mark above some or every `StaffGrp`. Put that too into `staff`? To me putting "system" and "staffgrp" as values into `@staff` it's like turning logic inside out. And what if it not above every `StaffGrp` but on the first and fourth? `@staff="staffgrp 1 4"`That would mix up with the "normal" logic of `@staff`. 
Again here is fundamental problem in `visual` and `logical` encoding. The tempo mark applies (normally) to all staves, but appears only above or below of some. `@plist` could be used to say to which this `<tempo>` applies, but if it is *one* tempo from start to end it probably would blow up your computer. 
Generally I think it is not a good idea to use a single element to encode several thinks. If there's a tempo mark above and below a 4-staff-system I would use two `<tempo>` elements instead of `@staff="1 4"`.

**Comment by pe-ro** [comment] 2017-05-21 14:04
@rettinghaus, Good points.

**Comment by ahankinson** [comment] 2017-05-21 20:48
Isn't a tempo marking essentially a milestone element? You don't have different tempos for different parallel staves -- it's a global change that appears once that effects all staves.

**Comment by rettinghaus** [comment] 2017-05-21 21:08
Actually there is plenty of music with different tempi on different staves. Take Steve Reich for example.

**Comment by craigsapp** [comment] 2017-05-21 21:11
> Isn't a tempo marking essentially a milestone element? You don't have different tempos for different parallel staves -- it's a global change that appears once that effects all staves.

In theory that is correct, but for orchestral scores, each group of the orchestra in the full score will have a separate display of the tempo marking (with potentally different vertical offsets to avoid notes in the staff the tempo marking is attached to).  Maybe this is more of a modern style, since two random orchestral scores on IMSLP do not have it:

<img width="746" alt="screen shot 2017-05-21 at 10 54 44 pm" src="https://cloud.githubusercontent.com/assets/3487289/26287317/4d9a156c-3e79-11e7-8a4f-f0eb2e097445.png">

But also note that the barlines go through all parts, so there are no staff groups in this case (and my internet connection is too slow to do more samples :-)

But in the second example, not the "Allegro non troppo" appears above and below the system:

<img width="727" alt="screen shot 2017-05-21 at 10 59 53 pm" src="https://cloud.githubusercontent.com/assets/3487289/26287326/693b4f98-3e79-11e7-83ce-1d28569107d6.png">

In a modern style, the bottom Allegro non troppo would appear above the first violins rather than under the contrabass part.  This is because the barlines group the woodwinds/brass into one group and the strings into a second group (by how the barlines connect the staves).

This also applies to tempo-related `<dir>s` as well (such as "rit." and "accel.").

> Isn't a tempo marking essentially a milestone element? You don't have different tempos for different parallel staves -- it's a global change that appears once that effects all staves.

Related to this: would the algorithm for extracting a part from a full score be to extract any tempo (found in the first staff typically) and include it on the staff being extracted for the part?

**Comment by ahankinson** [comment] 2017-05-21 21:19
So there is only one tempo, but where it's rendered is duplicated?

**Comment by craigsapp** [comment] 2017-05-21 21:22
Yes.  (not counting Charles Ives perhaps :-)

**Comment by craigsapp** [comment] 2017-05-21 21:30
> Actually there is plenty of music with different tempi on different staves. Take Steve Reich for example.

Is that a *de minimis* example?

**Comment by rettinghaus** [comment] 2017-05-21 21:39
It's really quite common in music after 1950. If you insist I'll look for some scans. 

> de minimis

**Comment by craigsapp** [comment] 2017-05-21 21:50
Anything after 1950 is under copyright, so you better not post them :-)

**Comment by pe-ro** [comment] 2017-05-23 22:17
MEI privileges the visual domain, so `@staff` indicates where the tempo marking **appears**.  In the Beethoven example, "Allegro non troppo" appears above the flutes and below the basses, which would require 2 different `<tempo>` elements since `@place` can only take 1 value at a time --

```
<tempo tstamp="1" place="above" staff="1">Allegro non troppo</tempo>
<tempo tstamp="1" place="below" staff="13">Allegro non troppo</tempo>
```

But let's assume for a moment that what we've got is a "modern" version of the score with the tempo marking appearing above the flutes and the violins.  In that case, we can get away with a short cut --
```
<tempo tstamp="1" place="above" staff="1 9">Allegro non troppo</tempo>
```
The question of "Which staves does this marking _apply to_?" must be addressed separately using `@plist` --
```
<tempo tstamp="1" place="above" staff="1 9" 
  plist="#staff1 #staff2">Allegro non troppo</tempo>
```
Of course, `@plist` requires the IDs of the staves, not their numbers.  Also, the appropriate values for `@plist` depend on which element it's attached to; that is, a tempo marking is likely to apply to staves, not notes, while an annotation can apply to any element.

**Comment by pe-ro** [comment] 2017-05-23 22:20
Playback of tempo markings is an entirely different thing, of course.  And, the audio realization of different tempos assigned to staves is mostly beyond what can be accomplished with MIDI anyway.

**Comment by ahankinson** [comment] 2017-05-23 23:52
Requiring the ID of staff would seem to require the ID of every `<staff>` within `<measure>` which would be pretty inefficient for sufficiently large scores and tempos of sufficient length. The plist for a tempo marking in an orchestral score could be huge!

Addressing `@n` would be better, but of course id-addressing doesn't consider anything other than `@xml:id`. And the behaviour of 'staff=1 9' isn't formalized in XML processing systems -- does that mean that the words are only attached to staff 1 & 9, or that the tempo only applies to those two staves? And what if it appears above staff 1 and below staff 9?

So it would seem a better solution would be required if you actually want to attach it to the precise staves (or measures?) and mix the visual, logical, and gestural ramifications of that marking into one element.

**Comment by lpugin** [comment] 2017-05-24 05:02
> The question of "Which staves does this marking apply to?" must be addressed separately using `@plist` --

On that topic I wondered a while ago if `@staff.ges` could be a way to go for this. Any thoughts?

**Comment by craigsapp** [comment] 2017-05-24 06:46
My original thoughts are related to score-level events rather than part-level events, with the primary motivation being categories of data such as harmony analysis, which applies to all parts even though it appears to be attached to a specific part (either the highest or lowest in the system).

In Humdrum I can attach harmonies to the score in two ways: attached to a particular staff, or attached to the score (system).

Here I attach it to the bottom staff:

<img width="559" alt="screen shot 2017-05-24 at 8 25 56 am" src="https://cloud.githubusercontent.com/assets/3487289/26389534/ad4f8fae-405a-11e7-8f42-12e11467f2e2.png">

Then the top staff:

<img width="545" alt="screen shot 2017-05-24 at 8 27 18 am" src="https://cloud.githubusercontent.com/assets/3487289/26389567/d228cc1e-405a-11e7-957a-3fb7273b252f.png">

And then to the system:

<img width="573" alt="screen shot 2017-05-24 at 8 28 03 am" src="https://cloud.githubusercontent.com/assets/3487289/26389589/f488e4ec-405a-11e7-9d21-17258f705253.png">

Notice that the first and third examples look visually the same, but they are semantically different. In Humdrum syntax, auxiliary spines to the right of the **kern spines are considered attached to that spine/part, while spines occurring to the left of the first **kern spines is considered attached to the system since it is not associated with any particular part.   When extracting a part, the system-level information may or may not be extracted along with the part information depending on the use of the extracted data.


-------------------------------


Tempo markings are a useful category to discuss as well.  Discussing with an analogy to other notation programs would be useful, particularly for functionality of generating parts from full scores (or perhaps the opposite direction as well).  In particular here is an example of how tempo markings (expressions) work in Finale.

First a full-score generated with Finale:

<img width="1079" alt="screen shot 2017-05-24 at 8 17 26 am" src="https://cloud.githubusercontent.com/assets/3487289/26389707/8f50848a-405b-11e7-8eda-fa1bcb7e7fcf.png">

In this case Finale adds a tempo marking "Allegro" to the top staff and to the strings group.

If I click on one of the tempo markings and change it to "Lento", then the other one automatically changes:

<img width="1040" alt="screen shot 2017-05-24 at 8 18 02 am" src="https://cloud.githubusercontent.com/assets/3487289/26389757/c884f20e-405b-11e7-85ac-bf80606f2007.png">


I can also edit the staff-assessment list for tempo markings (basically a "styling" for the `<tempo>` elements), and assign the tempo to be displayed on particular staves.  Here I add it above the brass section:

<img width="340" alt="screen shot 2017-05-24 at 8 20 00 am" src="https://cloud.githubusercontent.com/assets/3487289/26389810/033f5970-405c-11e7-8066-c858fd37c1e1.png">

Note that there are two columns for display of the tempo marking.  The first column is for which parts have the tempo displayed in the full score, and the second columns is for when to display it for an extracted part.  In this example all parts will have the tempo displayed due to the check at the top of the second column (otherwise you can uncheck that and check the parts which will have the tempo displayed in extraction on a case-by-case basis).

And then going back to the score display, the brass section includes the tempo marking:

<img width="1043" alt="screen shot 2017-05-24 at 8 20 56 am" src="https://cloud.githubusercontent.com/assets/3487289/26389827/167c702c-405c-11e7-8309-e47ca490bfef.png">

The tempo markings for each staff can be positioned independently (to avoid collisions with the content of the parts), so an XML-like system might be something like:

```xml
<tempo text="Allegro" hoffset="-10">
    <staff n="1" yoffset="10">
   <staff n="6" yoffset="20">
   <staff n="12" yoffset="0">
</tempo>
```

**Comment by pe-ro** [comment] 2017-05-24 17:45
Adding `@staff.ges` may indeed be the best way to add this functionality; that is, it can provide a way to attach stuff to staff numbers instead of staff IDs.  Here we could add "all".

**Comment by pe-ro** [comment] 2017-05-24 18:57
@craigsapp,
> The tempo markings for each staff can be positioned independently (to avoid collisions with the content of the parts), so an XML-like system might be something like:

Your example is XML, but it's not MEI; that is, it re-defines the meaning of `<staff>` when used inside `<tempo>` or other directive.  So, this is a non-starter.

**Comment by craigsapp** [comment] 2017-05-24 20:38
> Your example is XML, but it's not MEI; that is, it re-defines the meaning of <staff> when used inside <tempo> or other directive. So, this is a non-starter.

Hence I called it XML rather than MEI, so you are supposed to focus on the semantics rather than the syntax.

But in any case.  How would a case like this be encoded:

<img width="1022" alt="screen shot 2017-05-24 at 10 30 18 pm" src="https://cloud.githubusercontent.com/assets/3487289/26424262/e6e87e12-40d0-11e7-845d-58f7e32ef7a5.png">

Absalom fili mi, attributed to Josquin, c1500.

The finalis is on B-flat:

<img width="267" alt="screen shot 2017-05-24 at 10 35 57 pm" src="https://cloud.githubusercontent.com/assets/3487289/26424423/6e4e1150-40d1-11e7-9219-5574ba48cf6c.png">

**Comment by ahankinson** [comment] 2017-05-24 20:53
@craigsapp I think you're getting your conversations mixed up -- this one's about tempos. Key signatures are over on #434

**Comment by pe-ro** [comment] 2017-05-24 21:31
Regarding @lpugin's suggestion to use `@staff.ges`, I'm going to reverse my earlier statement and say that I don't think this is the way to go.  It puts this info in the gestural domain, where it doesn't really belong (it's not just performance-related), and where it can easily be eliminated by turning off the MEI.gestural module.  (It doesn't have to function this way, but all the other attributes with a name that ends in ".ges" do, so it would be odd if this one didn't.)  We also don't want to make it available everywhere `@staff` is by putting it in the `att.staffIdent` class.  I believe this new attribute, whatever it's called, only applies to control events, like `<tempo>`.

What we're trying to name is a part of the logical domain; that is, the attribute should record which staves are "affected by" the tempo marking, as opposed to those where the marking appears.  The problem is, having used `@staff` for the latter, we can't also use it for the former.  On the other hand, we can't rename `@staff` to `@staff.vis`, not only because of the consternation that would cause, but also because it wouldn't be completely true either since the definition of "logical" applies to the notation, not to the more abstract notion of musical logic.  It could also be eliminated along with other attributes ending in ".vis".  I'm also reluctant to call the new attribute `@staff.log` because that's only partially true as well.

So, I propose adding this new attribute to the `att.controlEvent` class where it will be inherited by all of the members of that class.  Now we just need a name that isn't `@staff`, `@staff.vis` or `@staff.log`.  Suggestions?

**Comment by kepper** [comment] 2017-05-25 09:02
staff.plist? staff.affected?

**Comment by pe-ro** [comment] 2017-05-25 14:11
`@staff.plist` (or perhaps `@plist.staff`?) is good.  It communicates the idea of participation like `@plist`, but also the restriction to staff participants.

**Comment by lpugin** [comment] 2017-05-25 18:07
I am a bit perplex if we cannot put this in one of the domain we have. I understand drawing the lines between the domains is always tricky. Also, it is clearly not a visual thing. But between logical, gestural or analytical I think it should find its place. Something like `@staff.plist` leaves it completely undefined and will introduce some significant confusion. Unless we want deliberately that it can apply to any domain, but then I am not sure it is useful.

**Comment by pe-ro** [comment] 2017-05-25 18:31
Sorry, I don't understand the source of your confusion.  No elements are in a domain; they're assigned to modules instead.  And there are many attributes that aren't in any domain, like `@plist` for example.  There's nothing magical about "domains", per se.  They're just a convenient way to group attributes.  That doesn't mean that every attribute has to be squarely in one domain or another.

The presence of `@plist.staff` (the name which I prefer) is mostly needed to provide information for the generation of parts, which doesn't fall into any domain.

Do you have an alternative name in mind for "the attribute that indicates the staff or staves to which a control event applies as opposed to the staff or staves with which it is visually associated"?  😀

**Comment by lpugin** [comment] 2017-05-25 19:02
> The presence of @plist.staff (the name which I prefer) is mostly needed to provide information for the generation of parts, which doesn't fall into any domain.

If we want to improve how parts are represented I would suggest to look at it at a broader level.

> Do you have an alternative name in mind for "the attribute that indicates the staff or staves to which a control event applies as opposed to the staff or staves with which it is visually associated"?

Yes, `@staff.ges` or probably better `@staff.log` 😀

**Comment by pe-ro** [comment] 2017-05-25 19:05
> Yes, `@staff.ges` or probably better `@staff.log` 😀

What does the generation of parts have to do with the gestural or logical domain?  And how are you defining "logical"?

Another option is to bag this whole thing and say that the generation of parts is currently outside the scope of MEI.  We provide markup for scores and markup for parts, but we don't say how to get from one to the other.

**Comment by craigsapp** [comment] 2017-05-25 19:09
> What does the generation of parts have to do with the gestural or logical domain?

The logical domain would be something that deals with the transformation of data from one form to another.  So attributes/elements needed for transforming score into parts or parts into scores could be involved with the logical domain.

**Comment by lpugin** [comment] 2017-05-25 19:26
> What does the generation of parts have to do with the gestural or logical domain? And how are you defining "logical"?

I understand the logical domain as the information that would let you transform a score into parts. But this is not a definition and I think having yours would be more useful to move forward.

**Comment by ahankinson** [comment] 2017-05-25 22:58
It seems like we run into the problem of typing relationships between elements often. I wonder if there can be a generic solution to this... something that allows us to relate two elements in the musical structure and give their relationship on a relator element, rather than trying to expand each element to accommodate a relationship type.

Something that allows us to say "tempo element x is in a logical relationship to staff y". That would link them without modifying either staff or tempo to accommodate every specific use case. 

A bit like how we can encode spanning elements outside of the hierarchy but still relate them.

**Comment by pe-ro** [comment] 2017-05-26 13:33
That element is called `<relation>`.

**Comment by pe-ro** [comment] 2017-05-26 14:32
Circling back around to give a more complete answer --

The `@plist` and `@target` attributes on `<relation>` can be used to identify the participants in a relationship, while `@rel` is used to identify the relationship between the participants.  Some bibliographic relationships (those defined by FRBR and MODS) are available out-of-the-box, but any relationship is possible.  `<relation>` isn't allowed everywhere, but is permitted in lots of places.

The new `<relation>` element is an improvement over creating special attributes for every kind of relationship, but it's not a panacea.  Generic markup like `<relation>` is difficult to constrain to specific uses.  For example, no matter how many relationships we name (by adding them as suggested values for `@rel`) there will always be an infinite number of possible relationships we haven't named.  In addition, it's often handier to have all the info about an entity (including its relationships to other entities) directly on the entity itself, instead of having to go elsewhere to look for relationships in which the entity may be a participant.

**Comment by pe-ro** [comment] 2017-09-05 19:51
This thread has got me thinking more generally about what additional info might be necessary to generate parts from an MEI score.  I think we've been circling around the idea that the meaning of `@staff` is overloaded.  

In order to help to resolve @craigsapp's original question and to separate out the various meanings (visual, logical, gestural) of `@staff`, what if we added a `@parts` attribute on control events, like `<dir>`, `<hairpin>`, `<tempo>`, etc.?  This new attribute is probably only necessary on a subset of all the possible control events, since some (like `<arpeg>`, `<pedal>`, etc.) only ever apply to a subset of staves.

I'm thinking `@parts` would only be allowed to take the value "all", meaning "place this control event in all generated parts regardless of the value(s) in `@staff`.  The absence of the `@parts` attribute would indicate that the control event applies only to the staves referenced in `@staff`.  For example --
```
<tempo tstamp="1" staff="1 12" place="above">Allegro</tempo>
```
retains its current meaning; that is, "Allegro" appears above staves 1 and 12 in the score, while 
```
<tempo tstamp="1" staff="1 12" place="above" parts="all">Allegro</tempo>
```
indicates that "Allegro" appears above staves 1 and 12, but should be placed in **all generated parts**.

The usual automatic and encoder-specified collision avoidance procedures (i.e., use of `@ho` and `@vo`) would have to be applied to each of the generated parts after their creation.

Another approach to generated parts is to allow the parts to be "template-like"; that is, along with the usual MEI content, they may contain instructions to copy elements from the score.  For example, a part may contain something like --
```
<part>
  <section>
    <measure n="1">
      <copy target="#tempo1">
        <copy-of select="@place"/>
        <attr name="tstamp">2</attr>
        <text>Allegretto</text>
      </copy>
    </measure>
  </section>
</part>
```
which provides instructions to copy the node called "tempo1" from the score and re-use its `@place` attribute, but replace its `@tstamp` attribute and its content.  This mechanism may also be useful for generic copying within score markup.  At present, I imagine the `<copy>` element would be useful within `<measure>` and `<layer>`.

If replacement of the element's content is not necessary, a processing-instruction can be used, for example --
```
<?copy target="#tempo1" keepattrs="place" tstamp="2" ?>
```
These are allowed to occur anywhere within XML content, but a parts-generator would have to understand the special syntax of the "copy" instruction.  In other words, a different parsing mechanism would have to be implemented for these instructions.

**Comment by pe-ro** [comment] 2017-09-06 13:31
Here's the ODD that implements the features described above --
```
<elementSpec ident="copy" module="MEI" mode="add">
  <desc>Copies only the node specified by the select attribute, i.e., a "shallow"
    copy.</desc>
  <classes>
    <memberOf key="att.id"/>
    <memberOf key="att.nNumberLike"/>
    <memberOf key="att.typed"/>
    <memberOf key="model.measurePart"/>
    <memberOf key="model.layerPart"/>
  </classes>
  <content>
    <rng:zeroOrMore>
      <rng:ref name="attr"/>
    </rng:zeroOrMore>
    <rng:zeroOrMore>
      <rng:choice>
        <rng:ref name="copy"/>
        <rng:ref name="copyof"/>
        <rng:ref name="elem"/>
      </rng:choice>
    </rng:zeroOrMore>
  </content>
  <attList>
    <attDef ident="select" usage="req">
      <datatype>
        <rng:text/>
      </datatype>
    </attDef>
  </attList>
</elementSpec>
<elementSpec ident="copyof" module="MEI" mode="add">
  <desc>Copies the node specified by the select attribute and its descendants, i.e., a 
    "deep" copy.</desc>
  <classes>
    <memberOf key="att.id"/>
    <memberOf key="att.nNumberLike"/>
    <memberOf key="att.typed"/>
  </classes>
  <content>
    <rng:empty/>
  </content>
  <attList>
    <attDef ident="select" usage="req">
      <datatype>
        <rng:text/>
      </datatype>
    </attDef>
  </attList>
</elementSpec>
<elementSpec ident="attr" module="MEI" mode="add">
  <desc>Used to add an attribute to the output.</desc>
  <classes>
    <memberOf key="att.id"/>
    <memberOf key="att.nNumberLike"/>
    <memberOf key="att.typed"/>
  </classes>
  <content>
    <rng:text/>
  </content>
  <attList>
    <attDef ident="name" usage="req">
      <datatype>
        <rng:text/>
      </datatype>
    </attDef>
  </attList>
</elementSpec>
<elementSpec ident="elem" module="MEI" mode="add">
  <desc>Used to add an element to the output.</desc>
  <classes>
    <memberOf key="att.id"/>
    <memberOf key="att.nNumberLike"/>
    <memberOf key="att.typed"/>
  </classes>
  <content>
    <rng:zeroOrMore>
      <rng:ref name="attr"/>
    </rng:zeroOrMore>
    <rng:zeroOrMore>
      <rng:choice>
        <rng:text/>
        <rng:ref name="elem"/>
      </rng:choice>
    </rng:zeroOrMore>
  </content>
  <attList>
    <attDef ident="name" usage="req">
      <datatype>
        <rng:text/>
      </datatype>
    </attDef>
  </attList>
</elementSpec>
```
With this in place, the following will validate --
```
<part>
  <section>
    <measure n="1">
      <staff>
        <layer>
          <!-- Copy a tempo marking from the score into this part -->
          <!--<tempo xml:id="tempo1" mm="120" mm.unit="8" mm.dots="1" 
            class="../../foo.bar#barfoo" analog="marc:foo"
            type="whatev" translit="wade-giles">Fast</tempo>-->
           <copy select="#tempo1">
            
            <!-- Make new attributes -->
            <attr name="xml:id">tempo1_a</attr>
            <attr name="foo">foo</attr>
            <attr name="bar">bar</attr>
            
            <!-- Copy existing attributes -->
            <copyof select="@* except @xml:id"/>
            
            <!-- Copy all descendants -->
            <copy select="*"/>

            <!-- Other operations that might be useful: -->
            <!-- Copy selected descendants -->
            <copy select="accid|label"/>
            
            <!-- Copy some elements from elsewhere -->
            <copy select="//measure[@n &lt; 3]"/>
            
            <!-- Make new descendant -->
            <elem name="beef">
              <attr name="flee">flee</attr>
              <attr name="fly">fly</attr>
              <attr name="flew">flew</attr>
              <elem name="burf">
                <attr name="burfle">burfle</attr>
              </elem>
            </elem>
          </copy>
        </layer>
      </staff>
    </measure>
  </section>
</part>
```
The syntax of the new elements is liberally borrowed from XSLT, so they should present no problems to someone familiar with that.  Copying and modifying during the copy process are both supported.  The value of the `@select` attribute is expected to be an XPath statement.

Of course, the example above is total nonsense.  The results of the copying/modifying process should make sense. Perhaps one could make sure of this by parsing the result against the mei-all_anyStart schema.

**Comment by kepper** [comment] 2017-09-07 10:43
I have some questions about this:

- How would this copy element relate to cpMark?
- If we introduce the term "parts" here, is it really sufficient to still think in staves, or do we have to consider layers (mostly for woodwinds etc.)?
- Is "all" really the only value we would need? What about "all strings", or "all from that staffGrp"?

**Comment by pe-ro** [comment] 2017-09-07 16:04
>Is "all" really the only value we would need? What about "all strings", or "all from that staffGrp"?

Suggesting `@parts` (perhaps better named as `@inparts` with a Boolean value) was intended to deal with the relatively simple case where we just want to indicate whether the directive should be copied into any **generated parts**.  The emphasis here is important -- technically, we can't reference any particular parts because they don't exist yet.

> If we introduce the term "parts" here, is it really sufficient to still think in staves, or do we have to consider layers (mostly for woodwinds etc.)?

Adding `<copy>` and `<copyof>` elements is intended to deal with the added complexity that is hinted at by your additional values "all strings" and "all from that staffGrp".  These elements provide more granular control over what gets copied and where.  An XPath in `@select` will make it possible to precisely identify the source material to be copied.  The `<copy>` and `<copyof>` elements themselves, in this case within a `<part>` element, identify the target location.

> How would this copy element relate to cpMark?

`<cpMark>` should be used to capture an editorial mark -- a number, a squiggly line, whatever -- that a scribe used to indicate that some material should get re-used in a different version of the source. `<copy>` and `<copyof>` are fancied-up processing instructions that operate in the absence of a scribal copy mark.  As proposed, they don't have anything to do with representing the source material.  However, I can imagine using `<copy>` and `<copyof>` to represent the realized result of a scribal copy mark; that is, to say "put the material here that the scribe indicated should be here when he used that copy mark."  In that case, we'd need a way of associating one or more `<copy>` or `<copyof>` elements (perhaps a group of them) with a `<cpMark>`.

**Comment by pe-ro** [comment] 2017-09-07 17:59
Revision to the proposed ODD --
```
<elementSpec ident="copy" module="MEI" mode="add">
  <desc>Copies only the node specified by the select attribute, not its attributes or descendants,
    i.e., a "shallow" copy.</desc>
  <classes>
    <memberOf key="att.id"/>
    <memberOf key="att.nNumberLike"/>
    <memberOf key="att.typed"/>
    <memberOf key="model.measurePart"/>
    <memberOf key="model.layerPart"/>
  </classes>
  <content>
    <rng:zeroOrMore>
      <rng:ref name="attr"/>
    </rng:zeroOrMore>
    <rng:zeroOrMore>
      <rng:choice>
        <rng:ref name="copy"/>
        <rng:ref name="copyof"/>
        <rng:ref name="elem"/>
      </rng:choice>
    </rng:zeroOrMore>
  </content>
  <attList>
    <attDef ident="select" usage="req">
      <desc>Contains an XPath expression.</desc>
      <datatype>
        <rng:text/>
      </datatype>
    </attDef>
  </attList>
</elementSpec>
<elementSpec ident="copyof" module="MEI" mode="add">
  <desc>Copies the node specified by the select attribute, as well as its attributes and
    descendants, i.e., a "deep" copy.</desc>
  <classes>
    <memberOf key="att.id"/>
    <memberOf key="att.nNumberLike"/>
    <memberOf key="att.typed"/>
  </classes>
  <content>
    <rng:empty/>
  </content>
  <attList>
    <attDef ident="select" usage="req">
      <desc>Contains an XPath expression.</desc>
      <datatype>
        <rng:text/>
      </datatype>
    </attDef>
  </attList>
</elementSpec>
<elementSpec ident="attr" module="MEI" mode="add">
  <desc>(attribute) – Used to add an attribute.</desc>
  <classes>
    <memberOf key="att.id"/>
    <memberOf key="att.nNumberLike"/>
    <memberOf key="att.typed"/>
  </classes>
  <content>
    <rng:text/>
  </content>
  <attList>
    <attDef ident="name" usage="req">
      <desc>Holds the name of the new attribute.</desc>
      <datatype>
        <rng:data type="NCName"/>
      </datatype>
    </attDef>
    <attDef ident="ns" usage="opt">
      <desc>(namespace) – Specifies the namespace to which the attribute belongs.</desc>
      <datatype>
        <rng:data type="anyURI">
          <rng:param name="pattern"
            >https?://[\-\da-z\.]+\.[\-\da-z\.]{2,6}([/\-\w\.]*)*/?</rng:param>
        </rng:data>
      </datatype>
    </attDef>
    <attDef ident="prefix" usage="opt">
      <desc>Declares a prefix associated with a namespace.</desc>
      <datatype>
        <rng:data type="NCName"/>
      </datatype>
    </attDef>
  </attList>
</elementSpec>
<elementSpec ident="elem" module="MEI" mode="add">
  <desc>(element)– Used to add an element.</desc>
  <classes>
    <memberOf key="att.id"/>
    <memberOf key="att.nNumberLike"/>
    <memberOf key="att.typed"/>
  </classes>
  <content>
    <rng:zeroOrMore>
      <rng:ref name="attr"/>
    </rng:zeroOrMore>
    <rng:zeroOrMore>
      <rng:choice>
        <rng:text/>
        <rng:ref name="elem"/>
      </rng:choice>
    </rng:zeroOrMore>
  </content>
  <attList>
    <attDef ident="name" usage="req">
      <desc>Holds the name of the new element.</desc>
      <datatype>
        <rng:data type="NCName"/>
      </datatype>
    </attDef>
    <attDef ident="ns" usage="opt">
      <desc>(namespace) – Specifies the namespace to which the element belongs.</desc>
      <datatype>
        <rng:data type="anyURI">
          <rng:param name="pattern"
            >https?://[\-\da-z\.]+\.[\-\da-z\.]{2,6}([/\-\w\.]*)*/?</rng:param>
        </rng:data>
      </datatype>
    </attDef>
    <attDef ident="prefix" usage="opt">
      <desc>Declares a prefix associated with a namespace.</desc>
      <datatype>
        <rng:data type="NCName"/>
      </datatype>
    </attDef>
  </attList>
</elementSpec>
```

**Comment by pe-ro** [comment] 2017-09-12 21:37
The relationship between a `<cpMark>` element and a `<copy>` or `<copyof>` element can be related using their respective `@corresp` attributes.

Of course, `@corresp` can deal with many-to-many relationships, so it's not a problem for a single `<cpMark>` to spawn multiple `<copy>` and `<copyof>` elements, as well as editorial elements, like `<supplied>` containing additional elements required by the move, such as `<octave>`.

There's some overlap between the `@origin.*` attributes on `<cpMark>` and the content of `<copy>` and `<copyof>`, but because they're using XPath, I think the new elements provide a better; that is, more granular, way to deal with material that cuts across hierarchical boundaries.

Contribution of real-world examples is highly desired. 😀

**Comment by pe-ro** [comment] 2017-10-13 23:08
The following ODD adds `@part` and `@partstaff` --
```
<classSpec ident="att.partIdent" module="MEI.shared" type="atts">
  <desc>Attributes for identifying the part associated with the current feature.</desc>
  <attList>
    <attDef ident="part" usage="opt">
      <desc>Indicates the part in which the current feature should appear.</desc>
      <datatype maxOccurs="unbounded">
        <rng:data type="NMTOKEN"/>
      </datatype>
    </attDef>
    <attDef ident="partstaff" usage="rec">
      <desc>Signifies the part staff on which a notated event occurs.</desc>
      <datatype maxOccurs="unbounded">
        <rng:data type="token">
          <rng:param name="pattern">\d+(-\d+)?(,\d+(-\d+)?)*</rng:param>
        </rng:data>
      </datatype>
    </attDef>
  </attList>
</classSpec>
```
which can be added to members of att.controlEvent --
```
<classSpec ident="att.controlEvent" module="MEI.shared" type="atts" mode="replace">
  <desc>Attributes shared by events which rely on other events for their existence. For example, a
    slur/phrase marking must be drawn between or over a group of notes. The slur is therefore a
    control event.</desc>
  <classes>
    <memberOf key="att.alignment"/>
    <memberOf key="att.layerIdent"/>
    <memberOf key="att.partIdent"/>
    <memberOf key="att.plist"/>
    <memberOf key="att.staffIdent"/>
    <memberOf key="att.targetEval"/>
    <memberOf key="att.timestamp.logical"/>
    <memberOf key="att.timestamp.gestural"/>
  </classes>
</classSpec>
```
This will allow `<tempo>`, etc. to specify which part and which staff within the part it belongs to.  For example --
```
<tempo tstamp="1" part="flute oboe trumpet">Allegro</tempo>
```
If `@partstaff` isn't present, staff no. 1 can be assumed. Alternatively, we could require `@partstaff` when `@part` is present.  Required or not, if `@partstaff` is present, it must have the same number of space-separated tokens as `@part` -- but I haven't written that constraint yet.

The parts may be virtual.  For instance, in the example above there may be no actual `<part>` elements that correspond to "flute", "oboe", or "trumpet".  On the other hand, if `@part` contains IDREFS; i.e.,
`#flute #oboe #trumpet`, then those would refer to `<part>` element IDs.  In either case, it might be useful to add a constraint that requires the tokens in `@part` to be unique, although I haven't yet provided that rule either.

This gives us a quick-and-dirty way to place control events in parts.  We can take up my earlier proposal to attack the issue the other way around later.  "The other way around" is when the part elements draw their content from the score encoding.

**Comment by pe-ro** [comment] 2017-11-02 21:01
In C'ville we decided to add `@part` and `@partstaff` on control events, like `<tempo>`, `<dir>`, `<slur>`, etc.  Doing this will satisfy @craigsapp 's original question.  For example,
```
<tempo tstamp="1" staff="1" part="%all" partstaff="%all">Allegro</tempo>
```
indicates that the "Allegro" marking occurs in the score on staff 1, but should also appear in all the parts, while
```
<tempo tstamp="1" staff="1" part="#strings #oboe" partstaff="1-3,5 1">Allegro</tempo>
```
means that the tempo marking occurs on staff 1 in the score, but should be associated with staves 1 through 3 and with staff 5 in the "strings" part as well as with staff 1 of the oboe part.  

Take note that there's no way to specify the placement of the marking; that is, above or below the staff, in the parts. There's also no check to make sure that there is actually a part called "strings" or "oboe" or that the staff numbers make sense.  Perhaps that could/should be done with Schematron later.

Here's the revised ODD that defines `@part` and `@partstaff` --
```
<classSpec ident="att.partIdent" module="MEI.shared" type="atts">
  <desc>Attributes for identifying the part in which the current feature appears.</desc>
  <attList>
    <attDef ident="part" usage="opt">
      <desc>Indicates the part in which the current feature should appear. Use '%all' when the
        feature should occur in every part.</desc>
      <datatype maxOccurs="unbounded">
        <rng:data type="token">
          <rng:param name="pattern">(%all|#[\i][\c]+)</rng:param>
        </rng:data>
      </datatype>
      <constraintSpec ident="check_part_attr_all" scheme="isoschematron">
        <constraint>
          <sch:rule context="@part[some $i in tokenize(., '\s+') satisfies (matches($i, '^%all$'))]">
            <sch:assert test="count(tokenize(., '\s+')) = 1">'%all' cannot be mixed with other
              values.</sch:assert>
          </sch:rule>
        </constraint>
      </constraintSpec>
    </attDef>
    <attDef ident="partstaff" usage="rec">
      <desc>Signifies the part staff on which a notated feature occurs. Use '%all' when the feature
        should occur on every staff.</desc>
      <datatype maxOccurs="unbounded">
        <rng:data type="token">
          <rng:param name="pattern">(%all|\d+(-\d+)?(,\d+(-\d+)?)*)</rng:param>
        </rng:data>
      </datatype>
      <constraintSpec ident="check_partstaff_attr_all" scheme="isoschematron">
        <constraint>
          <sch:rule
            context="@partstaff[some $i in tokenize(., '\s+') satisfies (matches($i, '^%all$'))]">
            <sch:assert test="count(tokenize(., '\s+')) = 1">'%all' cannot be mixed with other
              values.</sch:assert>
          </sch:rule>
        </constraint>
      </constraintSpec>
    </attDef>
  </attList>
</classSpec>
```
att.controlEvent is a member of att.partIdent, meaning everything that's a member of the controlEvent class inherits the attributes in att.partIdent.  A few other classes (annot.log, breath.log, caesura.log, lyrics.log, midi.event, midi.log, and reh.log) are also members of att.partIdent because their members are not members of att.controlEvent.

My other proposal (to add XSL-like `<copy>` and `<copyof>` elements) can be taken up again later.

**Closed as completed** 2017-11-08 19:30 UTC
Labels: Component: Core Schema, Priority: Medium, Type: Feature Request
