### ISSUE TITLE
Undefined variable on elements pages

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/music-encoding#1199] opened 2023-06-03 16:26 UTC
Using Chrome on MacOS, I get a javascript error when opening an element page:

https://music-encoding.org/guidelines/dev/elements/slur.html

<img width="1175" alt="Screenshot 2023-06-03 at 8 44 50 AM" src="https://github.com/music-encoding/music-encoding.github.io/assets/3487289/b24f98a3-9ef0-4736-ab14-bdf65ddad470">

This prevents changing the display style of the attributes list.

Here is the file line causing the problem:

<img width="923" alt="Screenshot 2023-06-03 at 8 45 49 AM" src="https://github.com/music-encoding/music-encoding.github.io/assets/3487289/5ef5edab-ddbf-41cd-bc66-b286e09ae0cb">

```javascript
        const newTab = document.getElementById(style + '_tab');
        newTab.classList.add('active');
```

where `newTab` is undefined.   `style` is an input parameter to the function (style is either null or there is no tab ID with the name `style + '_tab'`.

A similar problem (likely the same one) has occurred previously, related to the `localStorage` variables.  Here is what I see for the contents of `localStorage`:

<img width="666" alt="Screenshot 2023-06-03 at 8 50 18 AM" src="https://github.com/music-encoding/music-encoding.github.io/assets/3487289/43a2f695-ca91-4153-b1ba-bbab3ad9f234">

When I delete these variables and reload the page, the problem is fixed.  It seems that `localStorage.meiSpecs_attributes_display` is somehow causing the problem (and/or its value of `full`).

`localStorage` after deleting as well as reloading the page:

<img width="762" alt="Screenshot 2023-06-03 at 9 09 41 AM" src="https://github.com/music-encoding/music-encoding.github.io/assets/3487289/f82c3ca4-f5e1-43b9-a40b-d7968a677d34">

The value of `meiSpecs_attributes_display` is now changed from `full` to `attributes_full`.  Perhaps this is an interaction between older and newer versions of the guidelines (currently 3, 4, dev).   This seems the most likely problem, since viewing the version 4 page:

https://music-encoding.org/guidelines/v4/elements/slur.html#attributes

causes me a similar problem (but now in reverse) since the MEI4 version uses `full` for tab display and MEIdev uses `attributes_full`.

The solution to avoid this conflict  can be implemented in several ways.  And easy way would be to do something like `meiSpecs_mayContain_display_dev` where `_dev` is the development version of the guidelines.   Then v4 (and v3) can use the variable `meiSpecs_mayContain_display` or they could be updated to use `meiSpecs_mayContain_display_v4`, where there is a version tag in the variable name (derived by the URL piece that comes between `guidelines` and `elements`.

Another solution would be to either keep using `full` instead of `attributes_full`.  The `attributes_` tag is not necessary in the data string since the variable already contains it: `meiSpecs_attributes_display`, so the "attributes" scope is already understood.

Part of the solution should be to check if `newTab` is defined before using it, and also the solution would be mostly to keep track of the value of `style` when it is generated to see if it remains `null` after generating it.   This could also be related to the final solution where values of `full` and `attributes_full` could be automatically fixed based on the version (although above solutions are better).

Such as on line 1624 of the same page (for the current compiling of the website):

```javascript
const defaultValue = facetUl.children[0].children[0].getAttribute('data-display');
```

`defaultValue` should be checked to see if it is defined after this line, and deal with an undefined value (does not seem to be a problem in this case). `localStorage` is checked near this and if access is falsy the above code is run, but the final attributes style string is not checked for validity if it is not null (which is resulting in the cause of this problem).

**Comment by musicEnfanthen** [comment] 2023-06-05 21:26
Thanks @craigsapp for the report and investigation. 

Moving this issue to the main repo since it is related to the HTML guidelines that are generated from there.

**Comment by bwbohl** [comment] 2023-06-05 21:31
Hmm… interesting. That's something @pe-ro encountered on his machine during the developer workshop, but others could not reproduce it. Many thanks @craigsapp for the detailed inspection!

**Comment by bwbohl** [comment] 2023-06-05 22:50
@music-encoding/maintainers who can check this out?

**Comment by bwbohl** [comment] 2023-06-13 22:13
cannot reproduce on: MacOS Monterey 12.6.5
* Google Chrome version 114.0.5735.106 (Official Build) (arm64)
* Firefox 113.0.2 (64-bit

**Comment by musicEnfanthen** [comment] 2023-06-14 19:27
I can reproduce on Win 11 and FF when switching between dev and MEI 4 version of the guidelines. Local storage behaviour and tabs not working as reported by @craigsapp. When deleting the local storage, tabs are working again as expected.

**Closed as completed** 2023-07-04 13:44 UTC
Labels: Type: Bug

**Comment by musicEnfanthen** [comment] 2023-07-05 08:37
@craigsapp Can you please double-check if behaviour has improved after merge of #1219? At least for me, when switching between versions of the guidelines now, the tabs are still functional.
