### ISSUE TITLE
Encoding positioning of articulations

### ISSUE THREAD

**Issue by lpugin** [music-encoding/music-encoding#761] opened 2021-01-27 14:05 UTC
Some articulation signs, such as accents, are sometimes placed outside the staff, and sometimes inside.

![image](https://user-images.githubusercontent.com/689412/106001810-b315e800-60b0-11eb-854f-db9e49f79c31.png)

![image](https://user-images.githubusercontent.com/689412/106001895-c7f27b80-60b0-11eb-9076-949cc90cd79b.png)

How would this distinction be encoded?

**Comment by craigsapp** [comment] 2021-01-27 19:18
The second example is probably more common, so that could be the default.   Possibly an option could be used for the first example's rendering.  Otherwise an attribute could be added to MEI that would mean do not place the articulation inside of the staff (unless there is already such a thing).

If there were two layers of music, and the first measure of the example was in the second layer, then the second example is the only possible rendering (otherwise it would be similar to a recent fixed problem for automatic placement of trills and mordents attached to notes in the second layer).

**Comment by pe-ro** [comment] 2021-01-27 19:27
Not sure what you're asking but perhaps this will help --

Currently, layout positioning of articulations is addressed by `@loc` or with a combination of `@oloc` and `@ploc` on each `<artic>` element.  There is no way to assign values for a group of articulation signs.

**Comment by lpugin** [comment] 2021-01-27 19:48
@pe-ro `@oloc` and `@ploc` could work in some cases but I think we would rather have something that leaves it relative to the note pitches. In other words, it would not be necessary to change it if the clef is changed or if the notes are transposed. So I am thinking of an attribute like `@outside="true|false"`. I am sure we can find a better name, though.

**Comment by rettinghaus** [comment] 2021-01-27 19:58
Wouldn't be `place="within"` explicit enough for this?

**Comment by craigsapp** [comment] 2021-01-27 20:35
Currently in verovio `artic@place="above"` is relative to the note, not the staff.  So `within` does not have any particular meaning in this context (i.e., what does "within" a note mean?).  There could be additional placement qualifiers: `above within` which would allow the articulation to be placed above the note, and allowed to be within the staff (but only if necessary based on the pitch of the note).

A general problem is that some articulations are allowed within the staff (staccatos), tenutos and accents are usually allowed in, marcatos are usually outside of the staff, while others are rarely within (bowings), so it would be encoding verbosity to have to add `within` on every single articulation that can be inside of the staff.

This could be a scoreDef/staffDef attribute that sets the default withinness of articulation types when no explicit `within` is given on the articulation.  The goal would be to have music that can be transposed without changing placement attributes.  For example this is useful for converting between sounding score and transposing parts.

**Comment by lpugin** [comment] 2021-01-27 20:58
If we want to use `@place`, then I think we would need the following values:
* within
* above.within
* below.within
* outside
* above.outside
* below.outside

I don't think this is very elegant. Alternatively, as @craigsapp suggested, allow for multiple values in `@place`. Then the problem is how to make sure we do not have nonsense combinations. Things like `above below`, or `within outside`. Of course, Schematron can check this, but I don't think it is a very good solution either.

**Comment by pe-ro** [comment] 2021-01-27 22:12
Using `@place` to capture placement relative to the note AND to the staff is bad form.  Mea culpa.  However, adding more values to `@place` will, in my opinion, just create more confusion.  It would be better to add another attribute. My suggestion is `@staffPlace`, instead of @lpugin's `@outside`, with the currently allowed values of data.STAFFREL: 'above', 'below', 'between', and 'within'.  The new attribute would have to be used on every accid/artic where it's applicable, just like `@place` is used now.

Verbosity is the trade-off for explicitness.  As @craigsapp suggests, we could deal with that via a new attribute on `scoreDef` or `staffDef`, but that seems to me like it should be addressed as a separate issue.

While we're at it, the contextual nature of `@place` should be made explicit by making `@place` on `accid` and `artic` (plus others?) refer to a different datatype than `@place` elsewhere.

**Comment by lpugin** [comment] 2021-01-28 06:18
I don't think `@outside` was a particularly good proposal, so I am absolutely fine with something like `@staff.place` (I assume that would be the spelling). However, I am not sure I understand the argument against a boolean. Using `data.STAFFREL` does create confusion in my opinion. What would `between` mean in this context? Furthermore, it allows contradictory markup such as `<artic place="above" staff.place="below">`. Again, we can add a Schematron rule and I am fine with this if this is necessary. But I would like to understand its advantage over something like `@staff.within="true|false"` since this initial proposal was also about adding one attribute with an existing data type.

**Comment by pe-ro** [comment] 2021-01-28 16:16
Sorry, I missed your "outside as a boolean" proposal.  That will work too.

"staff.place" or "staff.within" are ok as names, but not 100% satisfactory, especially as we consider how to encode this concept at the staff or score level.  Still, I don't have a better name at the moment.  Whatever it's eventually called, it definitely belongs in the visual domain.

**Comment by pe-ro** [comment] 2021-01-29 10:18
There's currently an attribute in att.staffDef.vis called "ontheline".  In a similar vein, we could name the new attribute "onthestaff" or less verbosely "onstaff", e.g., `<artic onstaff="true">`.  If/when we get around to encoding this concept on staffDef and scoreDef (that is, to force positioning for all articulations for an entire staff or an entire score), the name could be 'artic.onstaff', e.g., `<staffDef artic.onstaff="false">`.

Question: Could/should this attribute also be applied to other elements, namely `<accid>`?  If so, we might have to rethink how we're capturing the positions of accidentals.

**Comment by lpugin** [comment] 2021-01-29 12:13
I like `onstaff` and `artic.onstaff` (which I think would be useful to have on staffDef).

I think it would make sense to have it on `accid` as well. I am not sure what would need to be rethought. It seems to me that it would work in the same way, except for the fact that this attribute would make sense only for editorial accidentals placed above (or rarely? below) the note. It seems that they are usually placed outside the staff, an this attribute would allow for them to be placed on the staff (but still above the note) when this is desired.

**Comment by pe-ro** [comment] 2021-01-29 19:03
I'll defer to you on making `onstaff` available on `accid`.  I just wasn't sure how the new attribute might affect how accidentals are already handled.  That is, there won't be any way to limit the use of the attribute to just editorial accidentals.  Perhaps we shouldn't think so narrowly; that is, there might be a case for allowing the placement of accidentals above the staff even when they're not editorial.

**Comment by craigsapp** [comment] 2021-01-29 19:48
> there might be a case for allowing the placement of accidentals above the staff even when they're not editorial.

Yes, this is a possibility.  I have see at least one case of a manuscript where there is an accidental written above the note, either because the scribe forgot about and added it later (not a different person correcting it), or more likely because they were running out of space, so they stuck the accidental above the note so that all of the notes could fit at the end of a line.

I have typeset a piece for a composer where the spacing between notes gives them duration, so in fast regions, the accidentals had to be moved above the notes.

**Comment by craigsapp** [comment] 2021-01-31 20:14
Here is an example of a turn that should be allowed within the staff (and above the note):

<img width="548" alt="Screen Shot 2021-01-31 at 12 12 37 PM" src="https://user-images.githubusercontent.com/3487289/106396599-c92bed00-63bd-11eb-9de5-80ed6c13f533.png">

With the default style for a turn with an accidental to be outside of the staff.

**Comment by lpugin** [comment] 2021-02-01 06:36
@pe-ro what should be the name of the `classSpec` for this attribute? `att.placementInside`?

**Comment by pe-ro** [comment] 2021-02-01 19:47
@craigsapp, the accidentals associated with a turn are recorded in attributes, i.e., `@accidupper` and `@accidlower`.  The turn's position is relative to the staff (above, below, between, or within).  The position of the accidental is relative to that of the turn.  There's no way to indicate the vertical position of the associated accidentals independent of the position of the turn.  In my opinion, attempting to replicate idiosyncratic notation like this is a never-ending chase.

**Comment by pe-ro** [comment] 2021-02-01 20:16
@lpugin, I would put the new attribute, `@onstaff`, along with `@place` (defined as vertical placement relative to the staff) into a new class called `att.placementRelEvent` and make `@artic.vis` a member of `att.placementRelEvent`.  I would also rename the current `att.placement` class to `att.placementRelStaff` and change any current references so that they use the new name.  This will clarify the contextual nature of `@place`.  That is, when `@place` is used on `<artic>` it means "relative to the event/note" and when used any where else it means "relative to the staff" (it's original meaning).

The same process can be applied to `<accid>`, although as I said in my response to @craigsapp, it won't apply to accidentals associated with a turn, trill, etc.

**Comment by craigsapp** [comment] 2021-02-01 22:03
> The turn's position is relative to the staff (above, below, between, or within). The position of the accidental is relative to that of the turn. There's no way to indicate the vertical position of the associated accidentals independent of the position of the turn. In my opinion, attempting to replicate idiosyncratic notation like this is a never-ending chase.

Yes, the placement within the staff would be for the turn (which includes the accidentals), not for the accidentals themselves.

**Comment by pe-ro** [comment] 2021-02-01 23:03
👍

**Comment by craigsapp** [comment] 2021-02-03 04:34
Here is a case of a dynamic within the staff:

<img width="126" alt="Screen Shot 2021-02-02 at 8 19 45 PM" src="https://user-images.githubusercontent.com/3487289/106697743-3beec100-6594-11eb-9807-03eb18e78e41.png">
from: 

https://verovio.humdrum.org/?k=ey&file=haydn/sonatas/sonata62-1.krn#mh14

placing it within the staff is mostly OK, but it would be clearer to say that it is below the note and allowed within the staff (otherwise, within the staff would imply trying to center it on the middle line of the staff).  Or if a dynamic is attached to a note with `@startid`, it could be allowed automatically inside of the staff when possible (I am attaching to the staff with `@tstamp` in the example).

**Comment by pe-ro** [comment] 2021-02-03 21:59
If the intention is to allow placement of other things relative to notes, such as dynamics,  as well as artics and accids, then we've got a different kettle of fish (as Laurel & Hardy used to say).

In that case, the different definitions of `@place` (relative to the note for artic & accid and relative to the staff or relative to the note for dynam & note) are in conflict.  We either 1) need different attributes, such as placeRelNote and placeRelStaff, 2) allow different/contextual definitions of `@place`, or 3) we have to allow `@place` to take all the possible values and let the renderer deal with the ambiguity.

One way out of this pickle is to define `@place` as "location of the item relative to the thing it's attached to."  In the case of `<dynam>`, if the attachment is encoded with `@tstamp`, then the value of `@place` is relative to the staff.  But, if the attachment is to a note or other event using `@startid`, then `@place` is relative to the event.  Since they're children of `<note>`, `<accid>` and `<artic>` would always be thought of as attached to a `<note>`.  Using this methodology, there would be no way (except via Schematron) to keep the user from encoding silly things, such as

```<accid accid="f" place="between" .../>```

Another possibility is to require a different kind of encoding when `<accid>` and `<artic>` are to be placed outside the staff.  That is, treat them as so-called "control events" -- things that are attached to the staff.  For instance,

```<dir startid="n1">(some kind of flat indicator here)</dir>```

There's even a possibility to make `<accid>` and `<artic>` control events themselves --

```
<accid startid="n1" accid="f"/>
or 
<accid tstamp="1.5" accid="f"/>
```
But, the additional attributes that come with being a member of the controlEvent class could cause problems that we'd need to address.

Even though it requires the encoder to "switch gears", the "control event" approach to things that fall outside the staff (including accid and artic sometimes) is unambiguous.

**Comment by lpugin** [comment] 2021-02-04 18:10
I think the proposal of having `att.placementRelEvent` for `artic` and `accid` and `att.placementRelStaff` for control events is a good start. 

I am not too convinced we need the `@onstaff` for `turn` and `dynam` even after seeing the two examples given by @craigsapp. The desired positioning remains unclear and it will quite likely not be very satisfactory. For the `turn`, what is on the staff is the accidental, not the turn itself. But maybe that would always be the expected positioning for turn?

**Comment by craigsapp** [comment] 2021-02-05 00:17
> But maybe that would always be the expected positioning for turn?

I would say that putting the accidental of the turn within the staff is less common, and mostly would be done to keep a tight spacing (maybe to allow the above system to be placed closer).   Also for delayed turns, the lacc should not be at the same diatonic step as the following note (contrary example given in third image below).

 If the turn is outside of the staff, generally the accidental will also be outside.  In this case:


<img width="548" alt="Screen Shot 2021-01-31 at 12 12 37 PM" src="https://user-images.githubusercontent.com/3487289/106396599-c92bed00-63bd-11eb-9de5-80ed6c13f533.png">


I think the typesetter wanted to horizontally align the three turns as much as possible, so they stuck the accidental inside the staff.   These are undelayed turns, so there is usually little opportunity for them to go inside of the staff.  Delayed turns probably are more permissive to get stuck inside the staff since it makes more sense for them to be between the two notes around it.


Of note, here is one that could in theory have the lacc within the staff, but it does not because it would be too crowded):
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata53-3.krn#mh24 (delayed, lacc, not within staff)

<img width="201" alt="Screen Shot 2021-02-04 at 3 56 56 PM" src="https://user-images.githubusercontent.com/3487289/106970418-a4a77c00-6701-11eb-92a0-607557c72d2a.png">


Here is one where the lacc natural is in the G5 position (so tip of natural is within staff), but cannot go inside of the staff due to the augmentation dot otherwise colliding with the turn:
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata59-1.krn#mh165 (delayed, lacc, kind of within staff)

<img width="130" alt="Screen Shot 2021-02-04 at 3 58 07 PM" src="https://user-images.githubusercontent.com/3487289/106970476-c86ac200-6701-11eb-9c02-cc0a86d581ee.png">

Example of the entire turn within the staff:
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata51-3.krn#mh5 (delayed, within staff)

<img width="126" alt="Screen Shot 2021-02-04 at 3 59 25 PM" src="https://user-images.githubusercontent.com/3487289/106970589-15e72f00-6702-11eb-8bf1-b48ea19188e3.png">


In the following case the lacc cannot go within the staff, because otherwise it would look like it is an accidental for the next note:

https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata53-3.krn#mh24 

<img width="103" alt="Screen Shot 2021-02-04 at 4 02 47 PM" src="https://user-images.githubusercontent.com/3487289/106970799-855d1e80-6702-11eb-85a3-8e4e7cac5ccb.png">

-------------------

[Press `alt-p` to see the source edition used to digitize following scores.]

Haydn sonata movements with turns (only ~25% are currently digitized, so not counting others to do):

https://verovio.humdrum.org?k=ey&file=haydn/sonatas/sonata12-1.krn
https://verovio.humdrum.org?k=ey&file=haydn/sonatas/sonata12-3.krn
https://verovio.humdrum.org?k=ey&file=haydn/sonatas/sonata15-1.krn
https://verovio.humdrum.org?k=ey&file=haydn/sonatas/sonata34-1.krn
https://verovio.humdrum.org?k=ey&file=haydn/sonatas/sonata37-1.krn
https://verovio.humdrum.org?k=ey&file=haydn/sonatas/sonata45-3a.krn
https://verovio.humdrum.org?k=ey&file=haydn/sonatas/sonata51-3.krn
https://verovio.humdrum.org?k=ey&file=haydn/sonatas/sonata52-3.krn
https://verovio.humdrum.org?k=ey&file=haydn/sonatas/sonata53-3.krn
https://verovio.humdrum.org?k=ey&file=haydn/sonatas/sonata59-1.krn
https://verovio.humdrum.org?k=ey&file=haydn/sonatas/sonata61-1.krn
https://verovio.humdrum.org?k=ey&file=haydn/sonatas/sonata62-1.krn


Mozart sonata movements with turns (digitized from Alte Mozart Ausgabe):
https://verovio.humdrum.org?k=ey&file=haydn/sonatas/sonata01-1.krn
https://verovio.humdrum.org?k=ey&file=haydn/sonatas/sonata03-3.krn
https://verovio.humdrum.org?k=ey&file=haydn/sonatas/sonata06-2.krn
https://verovio.humdrum.org?k=ey&file=haydn/sonatas/sonata06-3l.krn
https://verovio.humdrum.org?k=ey&file=haydn/sonatas/sonata07-2.krn
https://verovio.humdrum.org?k=ey&file=haydn/sonatas/sonata07-3.krn
https://verovio.humdrum.org?k=ey&file=haydn/sonatas/sonata08-2.krn
https://verovio.humdrum.org?k=ey&file=haydn/sonatas/sonata09-2.krn
https://verovio.humdrum.org?k=ey&file=haydn/sonatas/sonata10-2.krn
https://verovio.humdrum.org?k=ey&file=haydn/sonatas/sonata11-1f.krn
https://verovio.humdrum.org?k=ey&file=haydn/sonatas/sonata12-2.krn
https://verovio.humdrum.org?k=ey&file=haydn/sonatas/sonata13-3.krn
https://verovio.humdrum.org?k=ey&file=haydn/sonatas/sonata14-2.krn
https://verovio.humdrum.org?k=ey&file=haydn/sonatas/sonata14-3.krn


Beethoven sonata movements with turns (all sonatas digitized):
https://verovio.humdrum.org?k=ey&file=beethoven/sonatas/sonata01-2.krn
https://verovio.humdrum.org?k=ey&file=beethoven/sonatas/sonata01-4.krn
https://verovio.humdrum.org?k=ey&file=beethoven/sonatas/sonata02-1.krn
https://verovio.humdrum.org?k=ey&file=beethoven/sonatas/sonata02-2.krn
https://verovio.humdrum.org?k=ey&file=beethoven/sonatas/sonata02-4.krn
https://verovio.humdrum.org?k=ey&file=beethoven/sonatas/sonata03-1.krn
https://verovio.humdrum.org?k=ey&file=beethoven/sonatas/sonata03-2.krn
https://verovio.humdrum.org?k=ey&file=beethoven/sonatas/sonata07-2.krn
https://verovio.humdrum.org?k=ey&file=beethoven/sonatas/sonata19-1.krn
https://verovio.humdrum.org?k=ey&file=beethoven/sonatas/sonata19-2.krn
https://verovio.humdrum.org?k=ey&file=beethoven/sonatas/sonata20-1.krn
https://verovio.humdrum.org?k=ey&file=beethoven/sonatas/sonata24-1.krn
https://verovio.humdrum.org?k=ey&file=beethoven/sonatas/sonata26-1.krn
https://verovio.humdrum.org?k=ey&file=beethoven/sonatas/sonata28-1.krn


==========

Detailed list from Haydn sonatas, by measure.  Unlabeled ones are not delayed and have not lacc.  All are above the staff.

[Press alt-p to see the source edition used to digitize following scores.]

https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata12-1.krn#mh1
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata12-1.krn#mh21 (3 turns; with with lacc)
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata12-1.krn#mh38
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata12-3.krn#mh1
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata12-3.krn#mh2 (lacc within staff -- the above example))
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata12-3.krn#mh3
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata12-3.krn#mh4
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata12-3.krn#mh36
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata12-3.krn#mh37 (lacc within staff)
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata12-3.krn#mh38
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata12-3.krn#mh39
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata12-3.krn#mh45
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata12-3.krn#mh46
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata12-3.krn#mh47
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata15-1.krn#mh2 (delayed)
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata15-1.krn#mh6 (delayed)
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata15-1.krn#mh38 (delayed)
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata15-1.krn#mh55 (delayed)
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata15-1.krn#mh59 (delayed)
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata34-1.krn#mh61 (2 delayed with lacc)
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata34-1.krn#mh65 (2 delayed with lacc)
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata34-1.krn#mh71 (1 delayed with uacc)
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata34-1.krn#mh187 (2 delayed with lacc)
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata34-1.krn#mh191 (2 delayed with lacc)
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata37-1.krn#mh1 (lacc)
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata37-1.krn#mh3
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata37-1.krn#mh25
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata37-1.krn#mh31 (lacc)
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata37-1.krn#mh42 (lacc)
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata37-1.krn#mh44
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata45-3a.krn#mh3 (delayed with lacc)
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata51-3.krn#mh1 (delayed, within staff)
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata51-3.krn#mh5 (delayed, within staff)
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata51-3.krn#mh51 (delayed, not within staff)
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata51-3.krn#mh55
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata52-3.krn#mh37 (2 turns)
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata52-3.krn#mh39
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata52-3.krn#mh115 (2 turns)
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata52-3.krn#mh117 (under slur)
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata53-3.krn#mh24 (delayed, lacc, not within staff)
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata53-3.krn#mh29 (delayed, lacc, not within staff)
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata53-3.krn#mh33
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata53-3.krn#mh61 (delayed, lacc, not within staff)
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata53-3.krn#mh65 (delayed)
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata53-3.krn#mh119 (delayed, lacc)
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata59-1.krn#mh33 (lacc)
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata59-1.krn#mh35 (delayed, lacc)
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata59-1.krn#mh41 (lacc, not within staff)
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata59-1.krn#mh163 (lacc)
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata59-1.krn#mh165 (delayed, lacc, kind of within staff)
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata59-1.krn#mh171
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata61-1.krn#mh52 (lacc)
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata61-1.krn#mh88 (lacc)
https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata62-1.krn#mh97

----------------

I'll skip checking all of the Mozart and Beethoven turns, because I am only selectively OCD :-), but here is a Mozart turn where the lacc is within the staff:

https://verovio.humdrum.org/?k=ey&file=mozart/sonatas/sonata06-2.krn#mh74

<img width="771" alt="Screen Shot 2021-02-04 at 4 06 21 PM" src="https://user-images.githubusercontent.com/3487289/106971101-13390980-6703-11eb-9f46-f5c184abf4f3.png">

Note that if the lacc is within the staff, as in these two case, the lacc cannot align with the note that follows; otherwise, the accidental could be read as attached to the note rather than the turn.

but https://verovio.humdrum.org?ke=ey&file=haydn/sonatas/sonata59-1.krn#mh165 violates this rule.

**Comment by craigsapp** [comment] 2021-02-05 02:27
Here is an example of a turn within and below the staff:

<img width="74" alt="Screen Shot 2021-02-04 at 6 25 05 PM" src="https://user-images.githubusercontent.com/3487289/106981259-8f891800-6716-11eb-9aa9-94a93c4d87bc.png">

Meaasure 14 in:
https://kern.humdrum.org/cgi-bin/ksdata?file=sonata49-1.pdf&l=users/craig/classical/haydn/keyboard/uesonatas&format=pdf

**Comment by lpugin** [comment] 2021-02-05 12:33
Good examples. However, I think we are drifting away from the original issue. I would suggest to enhance `accid` and `artic` as suggested above. I'll make a PR - unless somebody opposes here. We can then open an issue - or rename this one - for turns or control events in general, which ever seems more appropriate. So please speak up if you disapprove or want more discussion on `artic` and `accid`.

**Comment by kepper** [comment] 2021-02-05 13:44
I think the proposal above seemed reasonable, so please go ahead and prepare a PR – we can have a fresh look at that and see where it brings us…

**Comment by pe-ro** [comment] 2021-02-05 16:27
Since  allowing turn, etc. to collide with the staff is still a possibility, I suggest the following:

1. rename the current att.placement class to `att.placementRelStaff` and make all current members except `<accid>` and `<artic>` members of the new class.  Here `@place` keeps its current definition: "Captures the placement of the item with respect to the staff with which it is associated."
2. create a new class called `att.placementRelEvent` and make `<accid>` and `<artic>` members of this class.  Contrary to what I said before, this class should only contain `@place` with a definition of "Captures the placement of the item with respect to the **event** with which it is associated."
3. create a new class `att.placementOnStaff` (not sure about the name) to hold the new attribute `@onStaff`.  Make `<accid>` and `<artic>` members of this class.

By placing `@place` and `@onStaff` into separate classes we have the ability to make the members of `att.placementRelStaff` members of `att.placementOnStaff` later, if necessary.

**Comment by ahankinson** [comment] 2021-03-05 11:02
@lpugin asked me to have a look at the issue and PR; the only suggestion I could make is that `@onstaff` be `@withinstaff` -- 'on' seems to indicate that it could be "on the staff line" (not really a good option, but the potential for confusion is there particularly since `@ontheline` is given as an example). 

In the original comment, the language of "inside" and "outside" was used, so this might be helpful to keep as it could indicate a natural way of talking about the style differences. According to @craigsapp 's comment, `@withinstaff="false"` would be the most likely expected behaviour.

**Closed as completed** 2021-03-26 13:50 UTC

**Comment by craigsapp** [comment] 2021-05-21 04:21
Here is an example related to accent marks (Chopin Op. 19,  mm1-3):

<img width="403" alt="Screen Shot 2021-05-20 at 9 11 44 PM" src="https://user-images.githubusercontent.com/3487289/119081320-9b8ca300-b9b0-11eb-84c8-762ff24a51f4.png">

The accents are overlapping notes in another voice, but should instead be placed in the E3 space.  In this case a placement of `below` should automatically be interpreted as below the note (or within the staff) rather than below the staff, since there is a voice/layer below the staff.

<details>
<summary>
Click to view MEI data for the above example.
</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2021-05-20T21:05:35" version="3.5.0-dev-a7f49d1-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
  <extMeta>
   <frames xmlns="http://www.humdrum.org/ns/humxml">
    <metaFrame n="11" token="!!!RDF**kern: &lt; = below" xml:id="L12">
     <frameInfo>
      <startTime float="4.5" ratfrac="1/2" />
      <frameType>reference</frameType>
      <referenceKey>RDF**kern</referenceKey>
      <referenceValue>&lt; = below</referenceValue>
     </frameInfo>
    </metaFrame>
   </frames>
  </extMeta>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mdiv-0000000538702874">
    <score xml:id="score-0000000145640173">
     <scoreDef xml:id="scoredef-0000001879019252">
      <staffGrp xml:id="staffgrp-0000000999530071" bar.thru="true" symbol="brace">
       <staffDef xml:id="staffdef-0000000479672940" n="1" lines="5">
        <clef xml:id="clef-L2F2" shape="G" line="2" />
        <meterSig xml:id="metersig-L3F2" count="3" unit="8" />
       </staffDef>
       <staffDef xml:id="staffdef-0000001972133080" n="2" lines="5">
        <clef xml:id="clef-L2F1" shape="F" line="4" />
        <meterSig xml:id="metersig-L3F1" count="3" unit="8" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1" n="1">
       <staff xml:id="staff-0000000043290271" n="1">
        <layer xml:id="layer-L1F2N1" n="1">
         <chord xml:id="chord-L5F2" dots="1" dur="4" stem.dir="up">
          <note xml:id="note-L5F2S1" oct="4" pname="g" accid.ges="n" />
          <note xml:id="note-L5F2S2" staff="2" oct="3" pname="g" accid.ges="n" />
          <artic xml:id="artic-L5F2" place="" artic="acc" />
         </chord>
        </layer>
       </staff>
       <staff xml:id="staff-0000001353423240" n="2">
        <layer xml:id="layer-L1F1N1" n="1">
         <chord xml:id="chord-L5F1" type="placed" dots="1" dur="4" stem.dir="down">
          <note xml:id="note-L5F1S1" oct="2" pname="g" accid.ges="n" />
          <note xml:id="note-L5F1S2" oct="1" pname="g" accid.ges="n" />
         </chord>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L6" n="2">
       <staff xml:id="staff-L6F2N1" n="1">
        <layer xml:id="layer-L6F2N1" n="1">
         <chord xml:id="chord-L7F2" dots="1" dur="4" stem.dir="up">
          <note xml:id="note-L7F2S1" oct="4" pname="g" accid.ges="n" />
          <note xml:id="note-L7F2S2" staff="2" oct="3" pname="g" accid.ges="n" />
          <artic xml:id="artic-L7F2" artic="acc" />
         </chord>
        </layer>
       </staff>
       <staff xml:id="staff-L6F1N1" n="2">
        <layer xml:id="layer-L6F1N1" n="1">
         <chord xml:id="chord-L7F1" type="placed" dots="1" dur="4" stem.dir="down">
          <note xml:id="note-L7F1S1" oct="2" pname="g" accid.ges="n" />
          <note xml:id="note-L7F1S2" oct="1" pname="g" accid.ges="n" />
         </chord>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L8" n="3">
       <staff xml:id="staff-L8F2N1" n="1">
        <layer xml:id="layer-L8F2N1" n="1">
         <chord xml:id="chord-L9F2" dots="1" dur="4" stem.dir="up">
          <note xml:id="note-L9F2S1" oct="4" pname="g" accid.ges="n" />
          <note xml:id="note-L9F2S2" staff="2" oct="3" pname="g" accid.ges="n" />
          <artic xml:id="artic-L9F2" artic="acc" />
         </chord>
        </layer>
       </staff>
       <staff xml:id="staff-L8F1N1" n="2">
        <layer xml:id="layer-L8F1N1" n="1">
         <chord xml:id="chord-L9F1" type="placed" dots="1" dur="4" stem.dir="down">
          <note xml:id="note-L9F1S1" oct="2" pname="g" accid.ges="n" />
          <note xml:id="note-L9F1S2" oct="1" pname="g" accid.ges="n" />
         </chord>
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

</details>
